/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "./vsrc/ps2_keyboard.v:1" *)
module ps2_keyboard(clk, rst, ps2_clk, ps2_data, seg0, seg1, seg2, seg3, seg4, seg5, seg6, seg7);
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire [3:0] _0000_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire [3:0] _0001_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire [3:0] _0002_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire [3:0] _0003_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire [3:0] _0004_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire [3:0] _0005_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire [9:0] _0006_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire _0007_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire [3:0] _0008_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire _0009_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire [7:0] _0010_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire _0011_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire _0012_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire _0013_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire _0014_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire _0015_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire _0016_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire _0017_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire _0018_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire _0019_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire _0020_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire _0021_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire _0022_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire _0023_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire _0024_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire _0025_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire _0026_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire _0027_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire _0028_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire _0029_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire _0030_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire _0031_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire _0032_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire _0033_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire _0034_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire _0035_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire _0036_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire _0037_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire _0038_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire _0039_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire _0040_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire _0041_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire _0042_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire _0043_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire _0044_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire _0045_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire _0046_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire _0047_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire _0048_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire _0049_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire _0050_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire _0051_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire _0052_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire _0053_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire _0054_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire _0055_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire _0056_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire _0057_;
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  wire _0058_;
  (* src = "./vsrc/ps2_keyboard.v:62" *)
  wire _0059_;
  (* src = "./vsrc/ps2_keyboard.v:62" *)
  wire _0060_;
  (* src = "./vsrc/ps2_keyboard.v:62" *)
  wire _0061_;
  (* src = "./vsrc/ps2_keyboard.v:62" *)
  wire _0062_;
  (* src = "./vsrc/ps2_keyboard.v:62" *)
  wire _0063_;
  (* src = "./vsrc/ps2_keyboard.v:62" *)
  wire _0064_;
  (* src = "./vsrc/ps2_keyboard.v:62" *)
  wire _0065_;
  (* src = "./vsrc/ps2_keyboard.v:62" *)
  wire _0066_;
  (* src = "./vsrc/ps2_keyboard.v:62" *)
  wire _0067_;
  (* src = "./vsrc/ps2_keyboard.v:62" *)
  wire _0068_;
  (* src = "./vsrc/ps2_keyboard.v:62" *)
  wire _0069_;
  (* src = "./vsrc/ps2_keyboard.v:62" *)
  wire _0070_;
  (* src = "./vsrc/ps2_keyboard.v:62" *)
  wire _0071_;
  (* src = "./vsrc/ps2_keyboard.v:62" *)
  wire _0072_;
  (* src = "./vsrc/ps2_keyboard.v:62" *)
  wire _0073_;
  (* src = "./vsrc/ps2_keyboard.v:62" *)
  wire _0074_;
  (* src = "./vsrc/ps2_keyboard.v:62" *)
  wire _0075_;
  (* src = "./vsrc/ps2_keyboard.v:62" *)
  wire _0076_;
  (* src = "./vsrc/ps2_keyboard.v:62" *)
  wire _0077_;
  (* src = "./vsrc/ps2_keyboard.v:62" *)
  wire _0078_;
  (* src = "./vsrc/ps2_keyboard.v:62" *)
  wire _0079_;
  (* src = "./vsrc/ps2_keyboard.v:62" *)
  wire _0080_;
  (* src = "./vsrc/ps2_keyboard.v:62" *)
  wire _0081_;
  (* src = "./vsrc/ps2_keyboard.v:62" *)
  wire _0082_;
  (* src = "./vsrc/ps2_keyboard.v:16" *)
  wire _0083_;
  (* src = "./vsrc/ps2_keyboard.v:16" *)
  wire _0084_;
  (* src = "./vsrc/ps2_keyboard.v:16" *)
  wire _0085_;
  (* src = "./vsrc/ps2_keyboard.v:16" *)
  wire _0086_;
  (* src = "./vsrc/ps2_keyboard.v:16" *)
  wire _0087_;
  (* src = "./vsrc/ps2_keyboard.v:16" *)
  wire _0088_;
  (* src = "./vsrc/ps2_keyboard.v:16" *)
  wire _0089_;
  (* src = "./vsrc/ps2_keyboard.v:16" *)
  wire _0090_;
  (* src = "./vsrc/ps2_keyboard.v:16" *)
  wire _0091_;
  (* src = "./vsrc/ps2_keyboard.v:16" *)
  wire _0092_;
  (* src = "./vsrc/ps2_keyboard.v:64" *)
  wire _0093_;
  (* src = "./vsrc/ps2_keyboard.v:17" *)
  wire _0094_;
  (* src = "./vsrc/ps2_keyboard.v:17" *)
  wire _0095_;
  (* src = "./vsrc/ps2_keyboard.v:17" *)
  wire _0096_;
  (* src = "./vsrc/ps2_keyboard.v:17" *)
  wire _0097_;
  (* src = "./vsrc/ps2_keyboard.v:90" *)
  wire _0098_;
  (* src = "./vsrc/ps2_keyboard.v:90" *)
  wire _0099_;
  (* src = "./vsrc/ps2_keyboard.v:90" *)
  wire _0100_;
  (* src = "./vsrc/ps2_keyboard.v:90" *)
  wire _0101_;
  (* src = "./vsrc/ps2_keyboard.v:90" *)
  wire _0102_;
  (* src = "./vsrc/ps2_keyboard.v:90" *)
  wire _0103_;
  (* src = "./vsrc/ps2_keyboard.v:90" *)
  wire _0104_;
  (* src = "./vsrc/ps2_keyboard.v:90" *)
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire _0414_;
  wire _0415_;
  wire _0416_;
  wire _0417_;
  wire _0418_;
  wire _0419_;
  wire _0420_;
  wire _0421_;
  wire _0422_;
  wire _0423_;
  wire _0424_;
  wire _0425_;
  wire _0426_;
  wire _0427_;
  wire _0428_;
  wire _0429_;
  wire _0430_;
  wire _0431_;
  (* src = "./vsrc/ps2_keyboard.v:65" *)
  wire _0432_;
  (* src = "./vsrc/ps2_keyboard.v:19" *)
  wire _0433_;
  (* src = "./vsrc/ps2_keyboard.v:19" *)
  wire _0434_;
  (* src = "./vsrc/ps2_keyboard.v:19" *)
  wire _0435_;
  (* src = "./vsrc/ps2_keyboard.v:19" *)
  wire _0436_;
  (* src = "./vsrc/ps2_keyboard.v:19" *)
  wire _0437_;
  (* src = "./vsrc/ps2_keyboard.v:19" *)
  wire _0438_;
  (* src = "./vsrc/ps2_keyboard.v:19" *)
  wire _0439_;
  (* src = "./vsrc/ps2_keyboard.v:19" *)
  wire _0440_;
  (* src = "./vsrc/ps2_keyboard.v:18" *)
  wire _0441_;
  (* src = "./vsrc/ps2_keyboard.v:18" *)
  wire _0442_;
  (* src = "./vsrc/ps2_keyboard.v:5" *)
  wire _0443_;
  (* src = "./vsrc/ps2_keyboard.v:3" *)
  wire _0444_;
  wire [3:0] _0445_;
  wire [2:0] _0446_;
  wire [3:0] _0447_;
  (* src = "./vsrc/ps2_keyboard.v:122" *)
  wire [3:0] _0448_;
  wire [7:0] _0449_;
  wire [31:0] _0450_;
  wire [31:0] _0451_;
  (* src = "./vsrc/ps2_keyboard.v:96" *)
  wire [31:0] _0452_;
  wire [1:0] _0453_;
  wire _0454_;
  wire [1:0] _0455_;
  wire _0456_;
  wire [1:0] _0457_;
  wire _0458_;
  wire [1:0] _0459_;
  wire _0460_;
  wire [1:0] _0461_;
  wire _0462_;
  wire [1:0] _0463_;
  wire _0464_;
  wire [1:0] _0465_;
  wire _0466_;
  wire [1:0] _0467_;
  wire _0468_;
  wire [1:0] _0469_;
  wire _0470_;
  wire [1:0] _0471_;
  wire _0472_;
  wire [3:0] _0473_;
  wire [1:0] _0474_;
  wire _0475_;
  wire _0476_;
  wire [3:0] _0477_;
  wire [1:0] _0478_;
  wire _0479_;
  wire [1:0] _0480_;
  wire _0481_;
  wire [3:0] _0482_;
  wire [3:0] _0483_;
  wire [3:0] _0484_;
  wire [3:0] _0485_;
  wire [3:0] _0486_;
  wire [3:0] _0487_;
  wire [3:0] _0488_;
  wire [3:0] _0489_;
  wire [3:0] _0490_;
  wire [3:0] _0491_;
  wire [7:0] _0492_;
  wire _0493_;
  wire _0494_;
  wire _0495_;
  wire _0496_;
  wire _0497_;
  wire _0498_;
  wire _0499_;
  wire _0500_;
  wire _0501_;
  wire _0502_;
  wire _0503_;
  (* src = "./vsrc/ps2_keyboard.v:85" *)
  wire _0504_;
  (* src = "./vsrc/ps2_keyboard.v:86" *)
  wire _0505_;
  (* src = "./vsrc/ps2_keyboard.v:93" *)
  wire _0506_;
  (* src = "./vsrc/ps2_keyboard.v:87" *)
  wire _0507_;
  (* src = "./vsrc/ps2_keyboard.v:88" *)
  wire _0508_;
  wire [7:0] _0509_;
  wire [7:0] _0510_;
  wire _0511_;
  (* src = "./vsrc/ps2_keyboard.v:96" *)
  wire _0512_;
  (* src = "./vsrc/ps2_keyboard.v:90" *)
  wire [7:0] _0513_;
  (* src = "./vsrc/ps2_keyboard.v:73" *)
  wire _0514_;
  wire _0515_;
  wire _0516_;
  wire _0517_;
  wire _0518_;
  wire _0519_;
  wire _0520_;
  wire _0521_;
  wire _0522_;
  wire _0523_;
  wire _0524_;
  wire _0525_;
  wire _0526_;
  wire _0527_;
  wire _0528_;
  wire _0529_;
  wire _0530_;
  wire _0531_;
  wire _0532_;
  wire _0533_;
  wire _0534_;
  wire _0535_;
  wire _0536_;
  wire _0537_;
  wire _0538_;
  wire _0539_;
  wire _0540_;
  wire _0541_;
  wire _0542_;
  wire _0543_;
  wire _0544_;
  wire _0545_;
  wire _0546_;
  wire _0547_;
  wire _0548_;
  wire _0549_;
  wire _0550_;
  wire _0551_;
  wire _0552_;
  wire _0553_;
  wire _0554_;
  wire _0555_;
  wire _0556_;
  wire _0557_;
  wire _0558_;
  wire _0559_;
  wire _0560_;
  wire _0561_;
  wire _0562_;
  wire _0563_;
  wire [3:0] _0564_;
  wire [3:0] _0565_;
  wire [3:0] _0566_;
  wire [3:0] _0567_;
  wire [3:0] _0568_;
  wire [3:0] _0569_;
  wire [3:0] _0570_;
  wire [3:0] _0571_;
  wire [3:0] _0572_;
  wire [3:0] _0573_;
  wire [3:0] _0574_;
  wire [3:0] _0575_;
  wire [3:0] _0576_;
  wire [3:0] _0577_;
  wire [3:0] _0578_;
  wire [3:0] _0579_;
  wire [3:0] _0580_;
  wire [3:0] _0581_;
  wire [3:0] _0582_;
  wire [3:0] _0583_;
  wire [3:0] _0584_;
  wire [3:0] _0585_;
  wire [3:0] _0586_;
  wire [3:0] _0587_;
  wire [3:0] _0588_;
  wire [3:0] _0589_;
  wire [3:0] _0590_;
  wire [3:0] _0591_;
  wire [7:0] _0592_;
  wire [7:0] _0593_;
  wire [7:0] _0594_;
  wire [7:0] _0595_;
  wire [3:0] _0596_;
  wire [3:0] _0597_;
  (* src = "./vsrc/ps2_keyboard.v:88" *)
  wire _0598_;
  (* src = "./vsrc/ps2_keyboard.v:122|<techmap.v>:246" *)
  wire [2:0] _0599_;
  (* src = "./vsrc/ps2_keyboard.v:122|<techmap.v>:257" *)
  wire [3:0] _0600_;
  (* src = "./vsrc/ps2_keyboard.v:122|<techmap.v>:253" *)
  wire [3:0] _0601_;
  (* src = "./vsrc/ps2_keyboard.v:122|<techmap.v>:247" *)
  wire [3:0] _0602_;
  (* src = "./vsrc/ps2_keyboard.v:122|<techmap.v>:258" *)
  wire [3:0] _0603_;
  (* src = "./vsrc/ps2_keyboard.v:122|<techmap.v>:250" *)
  wire _0604_;
  (* src = "./vsrc/ps2_keyboard.v:122|<techmap.v>:253" *)
  wire [3:0] _0605_;
  (* src = "./vsrc/ps2_keyboard.v:122|<techmap.v>:250" *)
  wire _0606_;
  (* src = "./vsrc/ps2_keyboard.v:122|<techmap.v>:251" *)
  wire [3:0] _0607_;
  (* src = "./vsrc/ps2_keyboard.v:122|<techmap.v>:248" *)
  wire [3:0] _0608_;
  (* src = "./vsrc/ps2_keyboard.v:122|<techmap.v>:248" *)
  wire [3:0] _0609_;
  (* src = "./vsrc/ps2_keyboard.v:122|<techmap.v>:260|<techmap.v>:198" *)
  wire _0610_;
  (* src = "./vsrc/ps2_keyboard.v:122|<techmap.v>:260|<techmap.v>:200" *)
  wire [3:0] _0611_;
  (* src = "./vsrc/ps2_keyboard.v:122|<techmap.v>:260|<techmap.v>:197" *)
  wire [3:0] _0612_;
  (* src = "./vsrc/ps2_keyboard.v:122|<techmap.v>:260|<techmap.v>:197" *)
  wire [3:0] _0613_;
  wire [1023:0] _0614_;
  (* src = "./vsrc/ps2_keyboard.v:122|<techmap.v>:260|<techmap.v>:203" *)
  wire [3:0] _0615_;
  (* src = "./vsrc/ps2_keyboard.v:122|<techmap.v>:260|<techmap.v>:202" *)
  wire [31:0] _0616_;
  (* src = "./vsrc/ps2_keyboard.v:122|<techmap.v>:260|<techmap.v>:202" *)
  wire [31:0] _0617_;
  (* src = "./vsrc/ps2_keyboard.v:122|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "1 2 3" *)
  wire [3:0] _0618_;
  wire [3:0] _0619_;
  wire [3:0] _0620_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:246" *)
  wire [7:0] _0621_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:257" *)
  wire [31:0] _0622_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:253" *)
  wire [31:0] _0623_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:247" *)
  wire [31:0] _0624_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:258" *)
  wire [31:0] _0625_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:250" *)
  wire _0626_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:253" *)
  wire [31:0] _0627_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:250" *)
  wire _0628_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:251" *)
  wire [31:0] _0629_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:248" *)
  wire [31:0] _0630_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:248" *)
  wire [31:0] _0631_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:198" *)
  wire _0632_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:200" *)
  wire [31:0] _0633_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:197" *)
  wire [31:0] _0634_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:197" *)
  wire [31:0] _0635_;
  wire [1023:0] _0636_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:203" *)
  wire [31:0] _0637_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:202" *)
  wire [31:0] _0638_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:202" *)
  wire [31:0] _0639_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _0640_;
  wire [31:0] _0641_;
  wire [31:0] _0642_;
  wire [7:0] _0643_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:246" *)
  wire [7:0] _0644_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:257" *)
  wire [7:0] _0645_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:253" *)
  wire [7:0] _0646_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:247" *)
  wire [7:0] _0647_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:258" *)
  wire [7:0] _0648_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:250" *)
  wire _0649_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:253" *)
  wire [7:0] _0650_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:250" *)
  wire _0651_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:251" *)
  wire [7:0] _0652_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:248" *)
  wire [7:0] _0653_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:248" *)
  wire [7:0] _0654_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:198" *)
  wire _0655_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:200" *)
  wire [7:0] _0656_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:197" *)
  wire [7:0] _0657_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:197" *)
  wire [7:0] _0658_;
  wire [1023:0] _0659_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:203" *)
  wire [7:0] _0660_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:202" *)
  wire [31:0] _0661_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:202" *)
  wire [31:0] _0662_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "1 2 3 4 5 6 7" *)
  wire [7:0] _0663_;
  wire [7:0] _0664_;
  wire [7:0] _0665_;
  wire _0666_;
  (* src = "./vsrc/ps2_keyboard.v:122|<techmap.v>:260" *)
  wire [3:0] _0667_;
  (* src = "./vsrc/ps2_keyboard.v:122|<techmap.v>:258" *)
  wire [3:0] _0668_;
  (* src = "./vsrc/ps2_keyboard.v:122|<techmap.v>:258" *)
  wire [3:0] _0669_;
  (* src = "./vsrc/ps2_keyboard.v:122|<techmap.v>:262" *)
  wire [3:0] _0670_;
  (* src = "./vsrc/ps2_keyboard.v:122|<techmap.v>:263" *)
  wire [4:0] _0671_;
  (* src = "./vsrc/ps2_keyboard.v:122|<techmap.v>:260|<techmap.v>:212" *)
  wire _0672_;
  (* src = "./vsrc/ps2_keyboard.v:122|<techmap.v>:260|<techmap.v>:221" *)
  wire _0673_;
  (* src = "./vsrc/ps2_keyboard.v:122|<techmap.v>:260|<techmap.v>:221" *)
  wire _0674_;
  (* src = "./vsrc/ps2_keyboard.v:122|<techmap.v>:260|<techmap.v>:221" *)
  wire _0675_;
  (* src = "./vsrc/ps2_keyboard.v:122|<techmap.v>:260|<techmap.v>:222" *)
  wire _0676_;
  (* src = "./vsrc/ps2_keyboard.v:122|<techmap.v>:260|<techmap.v>:229" *)
  wire _0677_;
  (* src = "./vsrc/ps2_keyboard.v:122|<techmap.v>:260|<techmap.v>:221" *)
  wire _0678_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260" *)
  wire [31:0] _0679_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:258" *)
  wire [31:0] _0680_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:258" *)
  wire [31:0] _0681_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:262" *)
  wire [31:0] _0682_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:263" *)
  wire [32:0] _0683_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:212" *)
  wire _0684_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0685_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0686_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0687_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0688_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0689_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0690_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0691_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0692_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0693_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0694_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0695_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0696_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0697_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0698_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0699_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0700_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0701_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0702_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0703_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0704_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0705_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0706_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0707_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0708_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0709_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0710_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0711_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0712_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0713_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0714_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0715_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:222" *)
  wire _0716_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:222" *)
  wire _0717_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:222" *)
  wire _0718_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:222" *)
  wire _0719_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:222" *)
  wire _0720_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:222" *)
  wire _0721_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:222" *)
  wire _0722_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:222" *)
  wire _0723_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:222" *)
  wire _0724_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:222" *)
  wire _0725_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:222" *)
  wire _0726_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:222" *)
  wire _0727_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:222" *)
  wire _0728_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:222" *)
  wire _0729_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:222" *)
  wire _0730_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:222" *)
  wire _0731_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:222" *)
  wire _0732_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:222" *)
  wire _0733_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:222" *)
  wire _0734_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:222" *)
  wire _0735_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:222" *)
  wire _0736_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:222" *)
  wire _0737_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:222" *)
  wire _0738_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:222" *)
  wire _0739_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:222" *)
  wire _0740_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:222" *)
  wire _0741_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:229" *)
  wire _0742_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:229" *)
  wire _0743_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:229" *)
  wire _0744_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:229" *)
  wire _0745_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:229" *)
  wire _0746_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:229" *)
  wire _0747_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:229" *)
  wire _0748_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:229" *)
  wire _0749_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:229" *)
  wire _0750_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:229" *)
  wire _0751_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:229" *)
  wire _0752_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:229" *)
  wire _0753_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:229" *)
  wire _0754_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:229" *)
  wire _0755_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:229" *)
  wire _0756_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:229" *)
  wire _0757_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:229" *)
  wire _0758_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:229" *)
  wire _0759_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:229" *)
  wire _0760_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:229" *)
  wire _0761_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:229" *)
  wire _0762_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:229" *)
  wire _0763_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:229" *)
  wire _0764_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:229" *)
  wire _0765_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:229" *)
  wire _0766_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:229" *)
  wire _0767_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0768_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0769_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0770_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0771_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0772_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0773_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0774_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0775_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0776_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0777_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0778_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0779_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0780_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0781_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0782_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0783_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0784_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0785_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0786_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0787_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0788_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0789_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0790_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0791_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0792_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0793_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260" *)
  wire [7:0] _0794_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:258" *)
  wire [7:0] _0795_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:258" *)
  wire [7:0] _0796_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:262" *)
  wire [7:0] _0797_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:263" *)
  wire [8:0] _0798_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:212" *)
  wire _0799_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0800_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0801_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0802_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0803_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0804_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0805_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0806_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:222" *)
  wire _0807_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:222" *)
  wire _0808_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:222" *)
  wire _0809_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:222" *)
  wire _0810_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:229" *)
  wire _0811_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:229" *)
  wire _0812_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:229" *)
  wire _0813_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:229" *)
  wire _0814_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0815_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0816_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0817_;
  (* src = "./vsrc/ps2_keyboard.v:96|<techmap.v>:260|<techmap.v>:221" *)
  wire _0818_;
  (* src = "./vsrc/ps2_keyboard.v:96" *)
  (* unused_bits = "8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _0819_;
  (* src = "./vsrc/ps2_keyboard.v:62" *)
  wire [3:0] bin_in0;
  (* src = "./vsrc/ps2_keyboard.v:62" *)
  wire [3:0] bin_in1;
  (* src = "./vsrc/ps2_keyboard.v:62" *)
  wire [3:0] bin_in2;
  (* src = "./vsrc/ps2_keyboard.v:62" *)
  wire [3:0] bin_in3;
  (* src = "./vsrc/ps2_keyboard.v:62" *)
  wire [3:0] bin_in4;
  (* src = "./vsrc/ps2_keyboard.v:62" *)
  wire [3:0] bin_in5;
  (* src = "./vsrc/ps2_keyboard.v:16" *)
  wire [9:0] buffer;
  (* src = "./vsrc/ps2_keyboard.v:64" *)
  wire check;
  (* src = "./vsrc/ps2_keyboard.v:2" *)
  input clk;
  (* src = "./vsrc/ps2_keyboard.v:17" *)
  wire [3:0] count;
  (* src = "./vsrc/ps2_keyboard.v:66" *)
  wire kill;
  (* src = "./vsrc/ps2_keyboard.v:65" *)
  wire off;
  (* src = "./vsrc/ps2_keyboard.v:19" *)
  wire [7:0] press_count;
  (* src = "./vsrc/ps2_keyboard.v:4" *)
  input ps2_clk;
  (* src = "./vsrc/ps2_keyboard.v:18" *)
  wire [2:0] ps2_clk_sync;
  (* src = "./vsrc/ps2_keyboard.v:5" *)
  input ps2_data;
  (* src = "./vsrc/ps2_keyboard.v:3" *)
  input rst;
  (* src = "./vsrc/ps2_keyboard.v:73" *)
  wire sampling;
  (* src = "./vsrc/ps2_keyboard.v:6" *)
  output [7:0] seg0;
  (* src = "./vsrc/ps2_keyboard.v:7" *)
  output [7:0] seg1;
  (* src = "./vsrc/ps2_keyboard.v:8" *)
  output [7:0] seg2;
  (* src = "./vsrc/ps2_keyboard.v:9" *)
  output [7:0] seg3;
  (* src = "./vsrc/ps2_keyboard.v:10" *)
  output [7:0] seg4;
  (* src = "./vsrc/ps2_keyboard.v:11" *)
  output [7:0] seg5;
  (* src = "./vsrc/ps2_keyboard.v:12" *)
  output [7:0] seg6;
  (* src = "./vsrc/ps2_keyboard.v:13" *)
  output [7:0] seg7;
  (* src = "./vsrc/ps2_keyboard.v:21" *)
  reg [7:0] rom [255:0];
  NOT _0820_ (
    .A(_0096_),
    .Y(_0106_)
  );
  NOT _0821_ (
    .A(_0095_),
    .Y(_0107_)
  );
  NOT _0822_ (
    .A(_0094_),
    .Y(_0108_)
  );
  NOT _0823_ (
    .A(_0440_),
    .Y(_0109_)
  );
  NOT _0824_ (
    .A(_0439_),
    .Y(_0110_)
  );
  NOT _0825_ (
    .A(_0438_),
    .Y(_0111_)
  );
  NOT _0826_ (
    .A(_0437_),
    .Y(_0112_)
  );
  NOT _0827_ (
    .A(_0436_),
    .Y(_0113_)
  );
  NOT _0828_ (
    .A(_0435_),
    .Y(_0114_)
  );
  NOT _0829_ (
    .A(_0434_),
    .Y(_0115_)
  );
  NOT _0830_ (
    .A(_0433_),
    .Y(_0116_)
  );
  NOT _0831_ (
    .A(_0097_),
    .Y(_0117_)
  );
  NOT _0832_ (
    .A(_0444_),
    .Y(_0118_)
  );
  NOT _0833_ (
    .A(_0093_),
    .Y(_0119_)
  );
  NOT _0834_ (
    .A(_0442_),
    .Y(_0120_)
  );
  NOT _0835_ (
    .A(_0083_),
    .Y(_0121_)
  );
  NOT _0836_ (
    .A(_0441_),
    .Y(_0122_)
  );
  NOT _0837_ (
    .A(_0092_),
    .Y(_0123_)
  );
  NOT _0838_ (
    .A(_0432_),
    .Y(_0124_)
  );
  NAND _0839_ (
    .A(_0090_),
    .B(_0091_),
    .Y(_0125_)
  );
  NOT _0840_ (
    .A(_0125_),
    .Y(_0126_)
  );
  NOR _0841_ (
    .A(_0090_),
    .B(_0091_),
    .Y(_0127_)
  );
  NOT _0842_ (
    .A(_0127_),
    .Y(_0128_)
  );
  NOR _0843_ (
    .A(_0126_),
    .B(_0127_),
    .Y(_0129_)
  );
  NAND _0844_ (
    .A(_0125_),
    .B(_0128_),
    .Y(_0130_)
  );
  NOR _0845_ (
    .A(_0123_),
    .B(_0129_),
    .Y(_0131_)
  );
  NAND _0846_ (
    .A(_0092_),
    .B(_0130_),
    .Y(_0132_)
  );
  NOR _0847_ (
    .A(_0092_),
    .B(_0130_),
    .Y(_0133_)
  );
  NAND _0848_ (
    .A(_0123_),
    .B(_0129_),
    .Y(_0134_)
  );
  NOR _0849_ (
    .A(_0131_),
    .B(_0133_),
    .Y(_0135_)
  );
  NAND _0850_ (
    .A(_0132_),
    .B(_0134_),
    .Y(_0136_)
  );
  NOR _0851_ (
    .A(_0086_),
    .B(_0087_),
    .Y(_0137_)
  );
  NOT _0852_ (
    .A(_0137_),
    .Y(_0138_)
  );
  NAND _0853_ (
    .A(_0086_),
    .B(_0087_),
    .Y(_0139_)
  );
  NOT _0854_ (
    .A(_0139_),
    .Y(_0140_)
  );
  NOR _0855_ (
    .A(_0137_),
    .B(_0140_),
    .Y(_0141_)
  );
  NAND _0856_ (
    .A(_0138_),
    .B(_0139_),
    .Y(_0142_)
  );
  NOR _0857_ (
    .A(_0085_),
    .B(_0084_),
    .Y(_0143_)
  );
  NOT _0858_ (
    .A(_0143_),
    .Y(_0144_)
  );
  NAND _0859_ (
    .A(_0085_),
    .B(_0084_),
    .Y(_0145_)
  );
  NOT _0860_ (
    .A(_0145_),
    .Y(_0146_)
  );
  NOR _0861_ (
    .A(_0143_),
    .B(_0146_),
    .Y(_0147_)
  );
  NAND _0862_ (
    .A(_0144_),
    .B(_0145_),
    .Y(_0148_)
  );
  NOR _0863_ (
    .A(_0142_),
    .B(_0147_),
    .Y(_0149_)
  );
  NAND _0864_ (
    .A(_0141_),
    .B(_0148_),
    .Y(_0150_)
  );
  NOR _0865_ (
    .A(_0141_),
    .B(_0148_),
    .Y(_0151_)
  );
  NAND _0866_ (
    .A(_0142_),
    .B(_0147_),
    .Y(_0152_)
  );
  NOR _0867_ (
    .A(_0149_),
    .B(_0151_),
    .Y(_0153_)
  );
  NAND _0868_ (
    .A(_0150_),
    .B(_0152_),
    .Y(_0154_)
  );
  NAND _0869_ (
    .A(_0089_),
    .B(_0088_),
    .Y(_0155_)
  );
  NOT _0870_ (
    .A(_0155_),
    .Y(_0156_)
  );
  NOR _0871_ (
    .A(_0089_),
    .B(_0088_),
    .Y(_0157_)
  );
  NOT _0872_ (
    .A(_0157_),
    .Y(_0158_)
  );
  NOR _0873_ (
    .A(_0156_),
    .B(_0157_),
    .Y(_0159_)
  );
  NAND _0874_ (
    .A(_0155_),
    .B(_0158_),
    .Y(_0160_)
  );
  NOR _0875_ (
    .A(_0154_),
    .B(_0160_),
    .Y(_0161_)
  );
  NAND _0876_ (
    .A(_0153_),
    .B(_0159_),
    .Y(_0162_)
  );
  NOR _0877_ (
    .A(_0153_),
    .B(_0159_),
    .Y(_0163_)
  );
  NAND _0878_ (
    .A(_0154_),
    .B(_0160_),
    .Y(_0164_)
  );
  NOR _0879_ (
    .A(_0161_),
    .B(_0163_),
    .Y(_0165_)
  );
  NAND _0880_ (
    .A(_0162_),
    .B(_0164_),
    .Y(_0166_)
  );
  NOR _0881_ (
    .A(_0135_),
    .B(_0166_),
    .Y(_0167_)
  );
  NAND _0882_ (
    .A(_0136_),
    .B(_0165_),
    .Y(_0168_)
  );
  NOR _0883_ (
    .A(_0136_),
    .B(_0165_),
    .Y(_0169_)
  );
  NAND _0884_ (
    .A(_0135_),
    .B(_0166_),
    .Y(_0170_)
  );
  NOR _0885_ (
    .A(_0167_),
    .B(_0169_),
    .Y(_0171_)
  );
  NAND _0886_ (
    .A(_0168_),
    .B(_0170_),
    .Y(_0172_)
  );
  NOR _0887_ (
    .A(_0107_),
    .B(_0094_),
    .Y(_0173_)
  );
  NAND _0888_ (
    .A(_0095_),
    .B(_0108_),
    .Y(_0174_)
  );
  NOR _0889_ (
    .A(_0096_),
    .B(_0117_),
    .Y(_0175_)
  );
  NAND _0890_ (
    .A(_0106_),
    .B(_0097_),
    .Y(_0176_)
  );
  NAND _0891_ (
    .A(_0173_),
    .B(_0175_),
    .Y(_0177_)
  );
  NOT _0892_ (
    .A(_0177_),
    .Y(_0178_)
  );
  NAND _0893_ (
    .A(_0121_),
    .B(_0443_),
    .Y(_0179_)
  );
  NOR _0894_ (
    .A(_0083_),
    .B(_0177_),
    .Y(_0180_)
  );
  NOR _0895_ (
    .A(_0177_),
    .B(_0179_),
    .Y(_0181_)
  );
  NAND _0896_ (
    .A(_0443_),
    .B(_0180_),
    .Y(_0182_)
  );
  NOR _0897_ (
    .A(_0171_),
    .B(_0182_),
    .Y(_0183_)
  );
  NAND _0898_ (
    .A(_0172_),
    .B(_0181_),
    .Y(_0184_)
  );
  NOR _0899_ (
    .A(_0120_),
    .B(_0441_),
    .Y(_0185_)
  );
  NAND _0900_ (
    .A(_0442_),
    .B(_0122_),
    .Y(_0186_)
  );
  NOR _0901_ (
    .A(_0184_),
    .B(_0186_),
    .Y(_0187_)
  );
  NAND _0902_ (
    .A(_0183_),
    .B(_0185_),
    .Y(_0188_)
  );
  NAND _0903_ (
    .A(_0118_),
    .B(_0187_),
    .Y(_0189_)
  );
  NOT _0904_ (
    .A(_0189_),
    .Y(_0190_)
  );
  NOR _0905_ (
    .A(_0444_),
    .B(_0186_),
    .Y(_0191_)
  );
  NAND _0906_ (
    .A(_0118_),
    .B(_0185_),
    .Y(_0192_)
  );
  NAND _0907_ (
    .A(_0061_),
    .B(_0189_),
    .Y(_0193_)
  );
  NOR _0908_ (
    .A(_0061_),
    .B(_0119_),
    .Y(_0194_)
  );
  NOR _0909_ (
    .A(_0093_),
    .B(_0086_),
    .Y(_0195_)
  );
  NOR _0910_ (
    .A(_0194_),
    .B(_0195_),
    .Y(_0196_)
  );
  NAND _0911_ (
    .A(_0137_),
    .B(_0143_),
    .Y(_0197_)
  );
  NOT _0912_ (
    .A(_0197_),
    .Y(_0198_)
  );
  NOR _0913_ (
    .A(_0125_),
    .B(_0155_),
    .Y(_0199_)
  );
  NOT _0914_ (
    .A(_0199_),
    .Y(_0200_)
  );
  NOR _0915_ (
    .A(_0197_),
    .B(_0200_),
    .Y(_0201_)
  );
  NAND _0916_ (
    .A(_0198_),
    .B(_0199_),
    .Y(_0202_)
  );
  NOR _0917_ (
    .A(_0188_),
    .B(_0201_),
    .Y(_0203_)
  );
  NAND _0918_ (
    .A(_0187_),
    .B(_0202_),
    .Y(_0204_)
  );
  NOR _0919_ (
    .A(_0444_),
    .B(_0204_),
    .Y(_0205_)
  );
  NAND _0920_ (
    .A(_0196_),
    .B(_0205_),
    .Y(_0206_)
  );
  NAND _0921_ (
    .A(_0193_),
    .B(_0206_),
    .Y(_0013_)
  );
  NAND _0922_ (
    .A(_0060_),
    .B(_0189_),
    .Y(_0207_)
  );
  NOR _0923_ (
    .A(_0060_),
    .B(_0119_),
    .Y(_0208_)
  );
  NOR _0924_ (
    .A(_0093_),
    .B(_0085_),
    .Y(_0209_)
  );
  NOR _0925_ (
    .A(_0208_),
    .B(_0209_),
    .Y(_0210_)
  );
  NAND _0926_ (
    .A(_0205_),
    .B(_0210_),
    .Y(_0211_)
  );
  NAND _0927_ (
    .A(_0207_),
    .B(_0211_),
    .Y(_0012_)
  );
  NAND _0928_ (
    .A(_0059_),
    .B(_0189_),
    .Y(_0212_)
  );
  NOR _0929_ (
    .A(_0059_),
    .B(_0119_),
    .Y(_0213_)
  );
  NOR _0930_ (
    .A(_0093_),
    .B(_0084_),
    .Y(_0214_)
  );
  NOR _0931_ (
    .A(_0213_),
    .B(_0214_),
    .Y(_0215_)
  );
  NAND _0932_ (
    .A(_0205_),
    .B(_0215_),
    .Y(_0216_)
  );
  NAND _0933_ (
    .A(_0212_),
    .B(_0216_),
    .Y(_0011_)
  );
  NOR _0934_ (
    .A(_0188_),
    .B(_0202_),
    .Y(_0217_)
  );
  NAND _0935_ (
    .A(_0187_),
    .B(_0201_),
    .Y(_0218_)
  );
  NAND _0936_ (
    .A(_0434_),
    .B(_0433_),
    .Y(_0219_)
  );
  NOT _0937_ (
    .A(_0219_),
    .Y(_0220_)
  );
  NOR _0938_ (
    .A(_0114_),
    .B(_0219_),
    .Y(_0221_)
  );
  NAND _0939_ (
    .A(_0435_),
    .B(_0220_),
    .Y(_0222_)
  );
  NOR _0940_ (
    .A(_0218_),
    .B(_0222_),
    .Y(_0223_)
  );
  NAND _0941_ (
    .A(_0217_),
    .B(_0221_),
    .Y(_0224_)
  );
  NAND _0942_ (
    .A(_0437_),
    .B(_0436_),
    .Y(_0225_)
  );
  NOT _0943_ (
    .A(_0225_),
    .Y(_0226_)
  );
  NAND _0944_ (
    .A(_0223_),
    .B(_0226_),
    .Y(_0227_)
  );
  NOT _0945_ (
    .A(_0227_),
    .Y(_0228_)
  );
  NOR _0946_ (
    .A(_0111_),
    .B(_0227_),
    .Y(_0229_)
  );
  NOR _0947_ (
    .A(_0116_),
    .B(_0218_),
    .Y(_0230_)
  );
  NAND _0948_ (
    .A(_0434_),
    .B(_0230_),
    .Y(_0231_)
  );
  NOR _0949_ (
    .A(_0439_),
    .B(_0229_),
    .Y(_0232_)
  );
  NAND _0950_ (
    .A(_0439_),
    .B(_0438_),
    .Y(_0233_)
  );
  NOR _0951_ (
    .A(_0110_),
    .B(_0225_),
    .Y(_0234_)
  );
  NOR _0952_ (
    .A(_0225_),
    .B(_0233_),
    .Y(_0235_)
  );
  NAND _0953_ (
    .A(_0438_),
    .B(_0234_),
    .Y(_0236_)
  );
  NOR _0954_ (
    .A(_0224_),
    .B(_0236_),
    .Y(_0237_)
  );
  NAND _0955_ (
    .A(_0223_),
    .B(_0235_),
    .Y(_0238_)
  );
  NAND _0956_ (
    .A(_0118_),
    .B(_0238_),
    .Y(_0239_)
  );
  NOR _0957_ (
    .A(_0232_),
    .B(_0239_),
    .Y(_0057_)
  );
  NAND _0958_ (
    .A(_0111_),
    .B(_0227_),
    .Y(_0240_)
  );
  NAND _0959_ (
    .A(_0118_),
    .B(_0240_),
    .Y(_0241_)
  );
  NOR _0960_ (
    .A(_0229_),
    .B(_0241_),
    .Y(_0056_)
  );
  NAND _0961_ (
    .A(_0436_),
    .B(_0223_),
    .Y(_0242_)
  );
  NAND _0962_ (
    .A(_0112_),
    .B(_0242_),
    .Y(_0243_)
  );
  NAND _0963_ (
    .A(_0118_),
    .B(_0243_),
    .Y(_0244_)
  );
  NOR _0964_ (
    .A(_0228_),
    .B(_0244_),
    .Y(_0055_)
  );
  NOR _0965_ (
    .A(_0436_),
    .B(_0223_),
    .Y(_0245_)
  );
  NOR _0966_ (
    .A(_0444_),
    .B(_0245_),
    .Y(_0246_)
  );
  NAND _0967_ (
    .A(_0242_),
    .B(_0246_),
    .Y(_0247_)
  );
  NOT _0968_ (
    .A(_0247_),
    .Y(_0054_)
  );
  NAND _0969_ (
    .A(_0114_),
    .B(_0231_),
    .Y(_0248_)
  );
  NAND _0970_ (
    .A(_0118_),
    .B(_0248_),
    .Y(_0249_)
  );
  NOR _0971_ (
    .A(_0223_),
    .B(_0249_),
    .Y(_0053_)
  );
  NOR _0972_ (
    .A(_0434_),
    .B(_0230_),
    .Y(_0250_)
  );
  NOR _0973_ (
    .A(_0444_),
    .B(_0250_),
    .Y(_0251_)
  );
  NAND _0974_ (
    .A(_0231_),
    .B(_0251_),
    .Y(_0252_)
  );
  NOT _0975_ (
    .A(_0252_),
    .Y(_0052_)
  );
  NAND _0976_ (
    .A(_0116_),
    .B(_0218_),
    .Y(_0253_)
  );
  NAND _0977_ (
    .A(_0118_),
    .B(_0253_),
    .Y(_0254_)
  );
  NOR _0978_ (
    .A(_0230_),
    .B(_0254_),
    .Y(_0051_)
  );
  NAND _0979_ (
    .A(_0095_),
    .B(_0094_),
    .Y(_0255_)
  );
  NOT _0980_ (
    .A(_0255_),
    .Y(_0256_)
  );
  NAND _0981_ (
    .A(_0096_),
    .B(_0256_),
    .Y(_0257_)
  );
  NOR _0982_ (
    .A(_0186_),
    .B(_0257_),
    .Y(_0258_)
  );
  NOR _0983_ (
    .A(_0192_),
    .B(_0255_),
    .Y(_0259_)
  );
  NAND _0984_ (
    .A(_0191_),
    .B(_0256_),
    .Y(_0260_)
  );
  NOR _0985_ (
    .A(_0106_),
    .B(_0444_),
    .Y(_0261_)
  );
  NOR _0986_ (
    .A(_0259_),
    .B(_0261_),
    .Y(_0262_)
  );
  NOR _0987_ (
    .A(_0258_),
    .B(_0262_),
    .Y(_0048_)
  );
  NOR _0988_ (
    .A(_0095_),
    .B(_0108_),
    .Y(_0263_)
  );
  NAND _0989_ (
    .A(_0185_),
    .B(_0263_),
    .Y(_0264_)
  );
  NOR _0990_ (
    .A(_0094_),
    .B(_0175_),
    .Y(_0265_)
  );
  NOT _0991_ (
    .A(_0265_),
    .Y(_0266_)
  );
  NAND _0992_ (
    .A(_0185_),
    .B(_0266_),
    .Y(_0267_)
  );
  NAND _0993_ (
    .A(_0095_),
    .B(_0267_),
    .Y(_0268_)
  );
  NAND _0994_ (
    .A(_0264_),
    .B(_0268_),
    .Y(_0269_)
  );
  NOT _0995_ (
    .A(_0269_),
    .Y(_0270_)
  );
  NOR _0996_ (
    .A(_0444_),
    .B(_0270_),
    .Y(_0047_)
  );
  NAND _0997_ (
    .A(_0178_),
    .B(_0185_),
    .Y(_0271_)
  );
  NAND _0998_ (
    .A(_0118_),
    .B(_0271_),
    .Y(_0272_)
  );
  NOR _0999_ (
    .A(_0108_),
    .B(_0185_),
    .Y(_0273_)
  );
  NOR _1000_ (
    .A(_0094_),
    .B(_0186_),
    .Y(_0274_)
  );
  NOR _1001_ (
    .A(_0273_),
    .B(_0274_),
    .Y(_0275_)
  );
  NOR _1002_ (
    .A(_0272_),
    .B(_0275_),
    .Y(_0046_)
  );
  NOR _1003_ (
    .A(_0077_),
    .B(_0203_),
    .Y(_0276_)
  );
  NAND _1004_ (
    .A(_0114_),
    .B(_0203_),
    .Y(_0277_)
  );
  NAND _1005_ (
    .A(_0118_),
    .B(_0277_),
    .Y(_0278_)
  );
  NOR _1006_ (
    .A(_0276_),
    .B(_0278_),
    .Y(_0029_)
  );
  NOR _1007_ (
    .A(_0076_),
    .B(_0203_),
    .Y(_0279_)
  );
  NAND _1008_ (
    .A(_0115_),
    .B(_0203_),
    .Y(_0280_)
  );
  NAND _1009_ (
    .A(_0118_),
    .B(_0280_),
    .Y(_0281_)
  );
  NOR _1010_ (
    .A(_0279_),
    .B(_0281_),
    .Y(_0028_)
  );
  NOR _1011_ (
    .A(_0075_),
    .B(_0203_),
    .Y(_0282_)
  );
  NAND _1012_ (
    .A(_0116_),
    .B(_0203_),
    .Y(_0283_)
  );
  NAND _1013_ (
    .A(_0118_),
    .B(_0283_),
    .Y(_0284_)
  );
  NOR _1014_ (
    .A(_0282_),
    .B(_0284_),
    .Y(_0027_)
  );
  NAND _1015_ (
    .A(_0065_),
    .B(_0189_),
    .Y(_0285_)
  );
  NAND _1016_ (
    .A(_0119_),
    .B(_0090_),
    .Y(_0286_)
  );
  NAND _1017_ (
    .A(_0093_),
    .B(_0065_),
    .Y(_0287_)
  );
  NAND _1018_ (
    .A(_0286_),
    .B(_0287_),
    .Y(_0288_)
  );
  NAND _1019_ (
    .A(_0205_),
    .B(_0288_),
    .Y(_0289_)
  );
  NAND _1020_ (
    .A(_0285_),
    .B(_0289_),
    .Y(_0017_)
  );
  NAND _1021_ (
    .A(_0064_),
    .B(_0189_),
    .Y(_0290_)
  );
  NAND _1022_ (
    .A(_0119_),
    .B(_0089_),
    .Y(_0291_)
  );
  NAND _1023_ (
    .A(_0093_),
    .B(_0064_),
    .Y(_0292_)
  );
  NAND _1024_ (
    .A(_0291_),
    .B(_0292_),
    .Y(_0293_)
  );
  NAND _1025_ (
    .A(_0205_),
    .B(_0293_),
    .Y(_0294_)
  );
  NAND _1026_ (
    .A(_0290_),
    .B(_0294_),
    .Y(_0016_)
  );
  NAND _1027_ (
    .A(_0063_),
    .B(_0189_),
    .Y(_0295_)
  );
  NAND _1028_ (
    .A(_0119_),
    .B(_0088_),
    .Y(_0296_)
  );
  NAND _1029_ (
    .A(_0093_),
    .B(_0063_),
    .Y(_0297_)
  );
  NAND _1030_ (
    .A(_0296_),
    .B(_0297_),
    .Y(_0298_)
  );
  NAND _1031_ (
    .A(_0205_),
    .B(_0298_),
    .Y(_0299_)
  );
  NAND _1032_ (
    .A(_0295_),
    .B(_0299_),
    .Y(_0015_)
  );
  NAND _1033_ (
    .A(_0073_),
    .B(_0189_),
    .Y(_0300_)
  );
  NAND _1034_ (
    .A(_0104_),
    .B(_0119_),
    .Y(_0301_)
  );
  NAND _1035_ (
    .A(_0073_),
    .B(_0093_),
    .Y(_0302_)
  );
  NAND _1036_ (
    .A(_0301_),
    .B(_0302_),
    .Y(_0303_)
  );
  NAND _1037_ (
    .A(_0205_),
    .B(_0303_),
    .Y(_0304_)
  );
  NAND _1038_ (
    .A(_0300_),
    .B(_0304_),
    .Y(_0025_)
  );
  NAND _1039_ (
    .A(_0072_),
    .B(_0189_),
    .Y(_0305_)
  );
  NAND _1040_ (
    .A(_0119_),
    .B(_0103_),
    .Y(_0306_)
  );
  NAND _1041_ (
    .A(_0072_),
    .B(_0093_),
    .Y(_0307_)
  );
  NAND _1042_ (
    .A(_0306_),
    .B(_0307_),
    .Y(_0308_)
  );
  NAND _1043_ (
    .A(_0205_),
    .B(_0308_),
    .Y(_0309_)
  );
  NAND _1044_ (
    .A(_0305_),
    .B(_0309_),
    .Y(_0024_)
  );
  NAND _1045_ (
    .A(_0071_),
    .B(_0189_),
    .Y(_0310_)
  );
  NAND _1046_ (
    .A(_0119_),
    .B(_0102_),
    .Y(_0311_)
  );
  NAND _1047_ (
    .A(_0071_),
    .B(_0093_),
    .Y(_0312_)
  );
  NAND _1048_ (
    .A(_0311_),
    .B(_0312_),
    .Y(_0313_)
  );
  NAND _1049_ (
    .A(_0205_),
    .B(_0313_),
    .Y(_0314_)
  );
  NAND _1050_ (
    .A(_0310_),
    .B(_0314_),
    .Y(_0023_)
  );
  NAND _1051_ (
    .A(_0069_),
    .B(_0189_),
    .Y(_0315_)
  );
  NAND _1052_ (
    .A(_0119_),
    .B(_0100_),
    .Y(_0316_)
  );
  NAND _1053_ (
    .A(_0093_),
    .B(_0069_),
    .Y(_0317_)
  );
  NAND _1054_ (
    .A(_0316_),
    .B(_0317_),
    .Y(_0318_)
  );
  NAND _1055_ (
    .A(_0205_),
    .B(_0318_),
    .Y(_0319_)
  );
  NAND _1056_ (
    .A(_0315_),
    .B(_0319_),
    .Y(_0021_)
  );
  NAND _1057_ (
    .A(_0068_),
    .B(_0189_),
    .Y(_0320_)
  );
  NAND _1058_ (
    .A(_0119_),
    .B(_0099_),
    .Y(_0321_)
  );
  NAND _1059_ (
    .A(_0093_),
    .B(_0068_),
    .Y(_0322_)
  );
  NAND _1060_ (
    .A(_0321_),
    .B(_0322_),
    .Y(_0323_)
  );
  NAND _1061_ (
    .A(_0205_),
    .B(_0323_),
    .Y(_0324_)
  );
  NAND _1062_ (
    .A(_0320_),
    .B(_0324_),
    .Y(_0020_)
  );
  NAND _1063_ (
    .A(_0067_),
    .B(_0189_),
    .Y(_0325_)
  );
  NAND _1064_ (
    .A(_0119_),
    .B(_0098_),
    .Y(_0326_)
  );
  NAND _1065_ (
    .A(_0093_),
    .B(_0067_),
    .Y(_0327_)
  );
  NAND _1066_ (
    .A(_0326_),
    .B(_0327_),
    .Y(_0328_)
  );
  NAND _1067_ (
    .A(_0205_),
    .B(_0328_),
    .Y(_0329_)
  );
  NAND _1068_ (
    .A(_0325_),
    .B(_0329_),
    .Y(_0019_)
  );
  NOR _1069_ (
    .A(_0081_),
    .B(_0203_),
    .Y(_0330_)
  );
  NAND _1070_ (
    .A(_0110_),
    .B(_0203_),
    .Y(_0331_)
  );
  NAND _1071_ (
    .A(_0118_),
    .B(_0331_),
    .Y(_0332_)
  );
  NOR _1072_ (
    .A(_0330_),
    .B(_0332_),
    .Y(_0033_)
  );
  NOR _1073_ (
    .A(_0080_),
    .B(_0203_),
    .Y(_0333_)
  );
  NAND _1074_ (
    .A(_0111_),
    .B(_0203_),
    .Y(_0334_)
  );
  NAND _1075_ (
    .A(_0118_),
    .B(_0334_),
    .Y(_0335_)
  );
  NOR _1076_ (
    .A(_0333_),
    .B(_0335_),
    .Y(_0032_)
  );
  NOR _1077_ (
    .A(_0079_),
    .B(_0203_),
    .Y(_0336_)
  );
  NAND _1078_ (
    .A(_0112_),
    .B(_0203_),
    .Y(_0337_)
  );
  NAND _1079_ (
    .A(_0118_),
    .B(_0337_),
    .Y(_0338_)
  );
  NOR _1080_ (
    .A(_0336_),
    .B(_0338_),
    .Y(_0031_)
  );
  NOR _1081_ (
    .A(_0444_),
    .B(_0264_),
    .Y(_0339_)
  );
  NAND _1082_ (
    .A(_0191_),
    .B(_0263_),
    .Y(_0340_)
  );
  NOR _1083_ (
    .A(_0176_),
    .B(_0340_),
    .Y(_0341_)
  );
  NAND _1084_ (
    .A(_0175_),
    .B(_0339_),
    .Y(_0342_)
  );
  NAND _1085_ (
    .A(_0443_),
    .B(_0341_),
    .Y(_0343_)
  );
  NAND _1086_ (
    .A(_0092_),
    .B(_0342_),
    .Y(_0344_)
  );
  NAND _1087_ (
    .A(_0343_),
    .B(_0344_),
    .Y(_0044_)
  );
  NOR _1088_ (
    .A(_0095_),
    .B(_0094_),
    .Y(_0345_)
  );
  NAND _1089_ (
    .A(_0107_),
    .B(_0108_),
    .Y(_0346_)
  );
  NOR _1090_ (
    .A(_0192_),
    .B(_0346_),
    .Y(_0347_)
  );
  NAND _1091_ (
    .A(_0191_),
    .B(_0345_),
    .Y(_0348_)
  );
  NOR _1092_ (
    .A(_0176_),
    .B(_0348_),
    .Y(_0349_)
  );
  NAND _1093_ (
    .A(_0175_),
    .B(_0347_),
    .Y(_0350_)
  );
  NAND _1094_ (
    .A(_0443_),
    .B(_0349_),
    .Y(_0351_)
  );
  NAND _1095_ (
    .A(_0091_),
    .B(_0350_),
    .Y(_0352_)
  );
  NAND _1096_ (
    .A(_0351_),
    .B(_0352_),
    .Y(_0043_)
  );
  NOR _1097_ (
    .A(_0106_),
    .B(_0097_),
    .Y(_0353_)
  );
  NAND _1098_ (
    .A(_0096_),
    .B(_0117_),
    .Y(_0354_)
  );
  NOR _1099_ (
    .A(_0260_),
    .B(_0354_),
    .Y(_0355_)
  );
  NAND _1100_ (
    .A(_0259_),
    .B(_0353_),
    .Y(_0356_)
  );
  NAND _1101_ (
    .A(_0443_),
    .B(_0355_),
    .Y(_0357_)
  );
  NAND _1102_ (
    .A(_0090_),
    .B(_0356_),
    .Y(_0358_)
  );
  NAND _1103_ (
    .A(_0357_),
    .B(_0358_),
    .Y(_0042_)
  );
  NOR _1104_ (
    .A(_0174_),
    .B(_0192_),
    .Y(_0359_)
  );
  NAND _1105_ (
    .A(_0173_),
    .B(_0191_),
    .Y(_0360_)
  );
  NOR _1106_ (
    .A(_0354_),
    .B(_0360_),
    .Y(_0361_)
  );
  NAND _1107_ (
    .A(_0353_),
    .B(_0359_),
    .Y(_0362_)
  );
  NAND _1108_ (
    .A(_0443_),
    .B(_0361_),
    .Y(_0363_)
  );
  NAND _1109_ (
    .A(_0089_),
    .B(_0362_),
    .Y(_0364_)
  );
  NAND _1110_ (
    .A(_0363_),
    .B(_0364_),
    .Y(_0041_)
  );
  NOR _1111_ (
    .A(_0340_),
    .B(_0354_),
    .Y(_0365_)
  );
  NAND _1112_ (
    .A(_0339_),
    .B(_0353_),
    .Y(_0366_)
  );
  NAND _1113_ (
    .A(_0443_),
    .B(_0365_),
    .Y(_0367_)
  );
  NAND _1114_ (
    .A(_0088_),
    .B(_0366_),
    .Y(_0368_)
  );
  NAND _1115_ (
    .A(_0367_),
    .B(_0368_),
    .Y(_0040_)
  );
  NOR _1116_ (
    .A(_0348_),
    .B(_0354_),
    .Y(_0369_)
  );
  NAND _1117_ (
    .A(_0347_),
    .B(_0353_),
    .Y(_0370_)
  );
  NAND _1118_ (
    .A(_0443_),
    .B(_0369_),
    .Y(_0371_)
  );
  NAND _1119_ (
    .A(_0087_),
    .B(_0370_),
    .Y(_0372_)
  );
  NAND _1120_ (
    .A(_0371_),
    .B(_0372_),
    .Y(_0039_)
  );
  NOR _1121_ (
    .A(_0096_),
    .B(_0097_),
    .Y(_0373_)
  );
  NAND _1122_ (
    .A(_0106_),
    .B(_0117_),
    .Y(_0374_)
  );
  NAND _1123_ (
    .A(_0259_),
    .B(_0373_),
    .Y(_0375_)
  );
  NOT _1124_ (
    .A(_0375_),
    .Y(_0376_)
  );
  NAND _1125_ (
    .A(_0443_),
    .B(_0376_),
    .Y(_0377_)
  );
  NAND _1126_ (
    .A(_0086_),
    .B(_0375_),
    .Y(_0378_)
  );
  NAND _1127_ (
    .A(_0377_),
    .B(_0378_),
    .Y(_0038_)
  );
  NOR _1128_ (
    .A(_0360_),
    .B(_0374_),
    .Y(_0379_)
  );
  NAND _1129_ (
    .A(_0359_),
    .B(_0373_),
    .Y(_0380_)
  );
  NAND _1130_ (
    .A(_0443_),
    .B(_0379_),
    .Y(_0381_)
  );
  NAND _1131_ (
    .A(_0085_),
    .B(_0380_),
    .Y(_0382_)
  );
  NAND _1132_ (
    .A(_0381_),
    .B(_0382_),
    .Y(_0037_)
  );
  NOR _1133_ (
    .A(_0340_),
    .B(_0374_),
    .Y(_0383_)
  );
  NAND _1134_ (
    .A(_0339_),
    .B(_0373_),
    .Y(_0384_)
  );
  NAND _1135_ (
    .A(_0443_),
    .B(_0383_),
    .Y(_0385_)
  );
  NAND _1136_ (
    .A(_0084_),
    .B(_0384_),
    .Y(_0386_)
  );
  NAND _1137_ (
    .A(_0385_),
    .B(_0386_),
    .Y(_0036_)
  );
  NOR _1138_ (
    .A(_0348_),
    .B(_0374_),
    .Y(_0387_)
  );
  NAND _1139_ (
    .A(_0347_),
    .B(_0373_),
    .Y(_0388_)
  );
  NAND _1140_ (
    .A(_0443_),
    .B(_0387_),
    .Y(_0389_)
  );
  NAND _1141_ (
    .A(_0083_),
    .B(_0388_),
    .Y(_0390_)
  );
  NAND _1142_ (
    .A(_0389_),
    .B(_0390_),
    .Y(_0035_)
  );
  NOR _1143_ (
    .A(_0093_),
    .B(_0201_),
    .Y(_0391_)
  );
  NAND _1144_ (
    .A(_0183_),
    .B(_0391_),
    .Y(_0392_)
  );
  NAND _1145_ (
    .A(_0432_),
    .B(_0185_),
    .Y(_0393_)
  );
  NAND _1146_ (
    .A(_0188_),
    .B(_0393_),
    .Y(_0394_)
  );
  NAND _1147_ (
    .A(_0392_),
    .B(_0394_),
    .Y(_0395_)
  );
  NOR _1148_ (
    .A(_0124_),
    .B(_0185_),
    .Y(_0396_)
  );
  NOR _1149_ (
    .A(_0444_),
    .B(_0396_),
    .Y(_0397_)
  );
  NAND _1150_ (
    .A(_0395_),
    .B(_0397_),
    .Y(_0050_)
  );
  NOR _1151_ (
    .A(_0093_),
    .B(_0190_),
    .Y(_0398_)
  );
  NOR _1152_ (
    .A(_0205_),
    .B(_0398_),
    .Y(_0045_)
  );
  NOR _1153_ (
    .A(_0082_),
    .B(_0203_),
    .Y(_0399_)
  );
  NAND _1154_ (
    .A(_0109_),
    .B(_0203_),
    .Y(_0400_)
  );
  NAND _1155_ (
    .A(_0118_),
    .B(_0400_),
    .Y(_0401_)
  );
  NOR _1156_ (
    .A(_0399_),
    .B(_0401_),
    .Y(_0034_)
  );
  NOR _1157_ (
    .A(_0078_),
    .B(_0203_),
    .Y(_0402_)
  );
  NAND _1158_ (
    .A(_0113_),
    .B(_0203_),
    .Y(_0403_)
  );
  NAND _1159_ (
    .A(_0118_),
    .B(_0403_),
    .Y(_0404_)
  );
  NOR _1160_ (
    .A(_0402_),
    .B(_0404_),
    .Y(_0030_)
  );
  NAND _1161_ (
    .A(_0074_),
    .B(_0189_),
    .Y(_0405_)
  );
  NAND _1162_ (
    .A(_0119_),
    .B(_0105_),
    .Y(_0406_)
  );
  NAND _1163_ (
    .A(_0093_),
    .B(_0074_),
    .Y(_0407_)
  );
  NAND _1164_ (
    .A(_0406_),
    .B(_0407_),
    .Y(_0408_)
  );
  NAND _1165_ (
    .A(_0205_),
    .B(_0408_),
    .Y(_0409_)
  );
  NAND _1166_ (
    .A(_0405_),
    .B(_0409_),
    .Y(_0026_)
  );
  NAND _1167_ (
    .A(_0070_),
    .B(_0189_),
    .Y(_0410_)
  );
  NAND _1168_ (
    .A(_0119_),
    .B(_0101_),
    .Y(_0411_)
  );
  NAND _1169_ (
    .A(_0093_),
    .B(_0070_),
    .Y(_0412_)
  );
  NAND _1170_ (
    .A(_0411_),
    .B(_0412_),
    .Y(_0413_)
  );
  NAND _1171_ (
    .A(_0205_),
    .B(_0413_),
    .Y(_0414_)
  );
  NAND _1172_ (
    .A(_0410_),
    .B(_0414_),
    .Y(_0022_)
  );
  NAND _1173_ (
    .A(_0066_),
    .B(_0189_),
    .Y(_0415_)
  );
  NAND _1174_ (
    .A(_0119_),
    .B(_0091_),
    .Y(_0416_)
  );
  NAND _1175_ (
    .A(_0093_),
    .B(_0066_),
    .Y(_0417_)
  );
  NAND _1176_ (
    .A(_0416_),
    .B(_0417_),
    .Y(_0418_)
  );
  NAND _1177_ (
    .A(_0205_),
    .B(_0418_),
    .Y(_0419_)
  );
  NAND _1178_ (
    .A(_0415_),
    .B(_0419_),
    .Y(_0018_)
  );
  NAND _1179_ (
    .A(_0062_),
    .B(_0189_),
    .Y(_0420_)
  );
  NAND _1180_ (
    .A(_0119_),
    .B(_0087_),
    .Y(_0421_)
  );
  NAND _1181_ (
    .A(_0093_),
    .B(_0062_),
    .Y(_0422_)
  );
  NAND _1182_ (
    .A(_0421_),
    .B(_0422_),
    .Y(_0423_)
  );
  NAND _1183_ (
    .A(_0205_),
    .B(_0423_),
    .Y(_0424_)
  );
  NAND _1184_ (
    .A(_0420_),
    .B(_0424_),
    .Y(_0014_)
  );
  NAND _1185_ (
    .A(_0109_),
    .B(_0238_),
    .Y(_0425_)
  );
  NAND _1186_ (
    .A(_0440_),
    .B(_0237_),
    .Y(_0426_)
  );
  NAND _1187_ (
    .A(_0425_),
    .B(_0426_),
    .Y(_0427_)
  );
  NOR _1188_ (
    .A(_0444_),
    .B(_0427_),
    .Y(_0058_)
  );
  NAND _1189_ (
    .A(_0097_),
    .B(_0258_),
    .Y(_0428_)
  );
  NOR _1190_ (
    .A(_0097_),
    .B(_0258_),
    .Y(_0429_)
  );
  NOT _1191_ (
    .A(_0429_),
    .Y(_0430_)
  );
  NAND _1192_ (
    .A(_0428_),
    .B(_0430_),
    .Y(_0431_)
  );
  NOR _1193_ (
    .A(_0272_),
    .B(_0431_),
    .Y(_0049_)
  );
  (* src = "./vsrc/ps2_keyboard.v:69" *)
  DFF _1194_ (
    .C(clk),
    .D(ps2_clk),
    .Q(ps2_clk_sync[0])
  );
  (* src = "./vsrc/ps2_keyboard.v:69" *)
  DFF _1195_ (
    .C(clk),
    .D(ps2_clk_sync[0]),
    .Q(ps2_clk_sync[1])
  );
  (* src = "./vsrc/ps2_keyboard.v:69" *)
  DFF _1196_ (
    .C(clk),
    .D(ps2_clk_sync[1]),
    .Q(ps2_clk_sync[2])
  );
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  DFF _1197_ (
    .C(clk),
    .D(_0007_),
    .Q(check)
  );
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  DFF _1198_ (
    .C(clk),
    .D(_0009_),
    .Q(off)
  );
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  DFF _1199_ (
    .C(clk),
    .D(_0005_[0]),
    .Q(bin_in5[0])
  );
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  DFF _1200_ (
    .C(clk),
    .D(_0005_[1]),
    .Q(bin_in5[1])
  );
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  DFF _1201_ (
    .C(clk),
    .D(_0005_[2]),
    .Q(bin_in5[2])
  );
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  DFF _1202_ (
    .C(clk),
    .D(_0005_[3]),
    .Q(bin_in5[3])
  );
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  DFF _1203_ (
    .C(clk),
    .D(_0004_[0]),
    .Q(bin_in4[0])
  );
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  DFF _1204_ (
    .C(clk),
    .D(_0004_[1]),
    .Q(bin_in4[1])
  );
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  DFF _1205_ (
    .C(clk),
    .D(_0004_[2]),
    .Q(bin_in4[2])
  );
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  DFF _1206_ (
    .C(clk),
    .D(_0004_[3]),
    .Q(bin_in4[3])
  );
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  DFF _1207_ (
    .C(clk),
    .D(_0003_[0]),
    .Q(bin_in3[0])
  );
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  DFF _1208_ (
    .C(clk),
    .D(_0003_[1]),
    .Q(bin_in3[1])
  );
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  DFF _1209_ (
    .C(clk),
    .D(_0003_[2]),
    .Q(bin_in3[2])
  );
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  DFF _1210_ (
    .C(clk),
    .D(_0003_[3]),
    .Q(bin_in3[3])
  );
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  DFF _1211_ (
    .C(clk),
    .D(_0002_[0]),
    .Q(bin_in2[0])
  );
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  DFF _1212_ (
    .C(clk),
    .D(_0002_[1]),
    .Q(bin_in2[1])
  );
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  DFF _1213_ (
    .C(clk),
    .D(_0002_[2]),
    .Q(bin_in2[2])
  );
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  DFF _1214_ (
    .C(clk),
    .D(_0002_[3]),
    .Q(bin_in2[3])
  );
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  DFF _1215_ (
    .C(clk),
    .D(_0001_[0]),
    .Q(bin_in1[0])
  );
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  DFF _1216_ (
    .C(clk),
    .D(_0001_[1]),
    .Q(bin_in1[1])
  );
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  DFF _1217_ (
    .C(clk),
    .D(_0001_[2]),
    .Q(bin_in1[2])
  );
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  DFF _1218_ (
    .C(clk),
    .D(_0001_[3]),
    .Q(bin_in1[3])
  );
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  DFF _1219_ (
    .C(clk),
    .D(_0000_[0]),
    .Q(bin_in0[0])
  );
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  DFF _1220_ (
    .C(clk),
    .D(_0000_[1]),
    .Q(bin_in0[1])
  );
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  DFF _1221_ (
    .C(clk),
    .D(_0000_[2]),
    .Q(bin_in0[2])
  );
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  DFF _1222_ (
    .C(clk),
    .D(_0000_[3]),
    .Q(bin_in0[3])
  );
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  DFF _1223_ (
    .C(clk),
    .D(_0010_[0]),
    .Q(press_count[0])
  );
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  DFF _1224_ (
    .C(clk),
    .D(_0010_[1]),
    .Q(press_count[1])
  );
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  DFF _1225_ (
    .C(clk),
    .D(_0010_[2]),
    .Q(press_count[2])
  );
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  DFF _1226_ (
    .C(clk),
    .D(_0010_[3]),
    .Q(press_count[3])
  );
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  DFF _1227_ (
    .C(clk),
    .D(_0010_[4]),
    .Q(press_count[4])
  );
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  DFF _1228_ (
    .C(clk),
    .D(_0010_[5]),
    .Q(press_count[5])
  );
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  DFF _1229_ (
    .C(clk),
    .D(_0010_[6]),
    .Q(press_count[6])
  );
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  DFF _1230_ (
    .C(clk),
    .D(_0010_[7]),
    .Q(press_count[7])
  );
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  DFF _1231_ (
    .C(clk),
    .D(_0008_[0]),
    .Q(count[0])
  );
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  DFF _1232_ (
    .C(clk),
    .D(_0008_[1]),
    .Q(count[1])
  );
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  DFF _1233_ (
    .C(clk),
    .D(_0008_[2]),
    .Q(count[2])
  );
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  DFF _1234_ (
    .C(clk),
    .D(_0008_[3]),
    .Q(count[3])
  );
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  DFF _1235_ (
    .C(clk),
    .D(_0006_[0]),
    .Q(buffer[0])
  );
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  DFF _1236_ (
    .C(clk),
    .D(_0006_[1]),
    .Q(buffer[1])
  );
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  DFF _1237_ (
    .C(clk),
    .D(_0006_[2]),
    .Q(buffer[2])
  );
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  DFF _1238_ (
    .C(clk),
    .D(_0006_[3]),
    .Q(buffer[3])
  );
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  DFF _1239_ (
    .C(clk),
    .D(_0006_[4]),
    .Q(buffer[4])
  );
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  DFF _1240_ (
    .C(clk),
    .D(_0006_[5]),
    .Q(buffer[5])
  );
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  DFF _1241_ (
    .C(clk),
    .D(_0006_[6]),
    .Q(buffer[6])
  );
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  DFF _1242_ (
    .C(clk),
    .D(_0006_[7]),
    .Q(buffer[7])
  );
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  DFF _1243_ (
    .C(clk),
    .D(_0006_[8]),
    .Q(buffer[8])
  );
  (* src = "./vsrc/ps2_keyboard.v:75" *)
  DFF _1244_ (
    .C(clk),
    .D(_0006_[9]),
    .Q(buffer[9])
  );
  (* src = "./vsrc/ps2_keyboard.v:23" *)
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\rom"),
    .PRIORITY(32'd112),
    .WIDTH(32'd8),
    .WORDS(32'd1)
  ) _1245_ (
    .ADDR(32'd28),
    .DATA(8'h41)
  );
  (* src = "./vsrc/ps2_keyboard.v:24" *)
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\rom"),
    .PRIORITY(32'd113),
    .WIDTH(32'd8),
    .WORDS(32'd1)
  ) _1246_ (
    .ADDR(32'd50),
    .DATA(8'h42)
  );
  (* src = "./vsrc/ps2_keyboard.v:25" *)
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\rom"),
    .PRIORITY(32'd114),
    .WIDTH(32'd8),
    .WORDS(32'd1)
  ) _1247_ (
    .ADDR(32'd33),
    .DATA(8'h43)
  );
  (* src = "./vsrc/ps2_keyboard.v:26" *)
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\rom"),
    .PRIORITY(32'd115),
    .WIDTH(32'd8),
    .WORDS(32'd1)
  ) _1248_ (
    .ADDR(32'd35),
    .DATA(8'h44)
  );
  (* src = "./vsrc/ps2_keyboard.v:27" *)
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\rom"),
    .PRIORITY(32'd116),
    .WIDTH(32'd8),
    .WORDS(32'd1)
  ) _1249_ (
    .ADDR(32'd36),
    .DATA(8'h45)
  );
  (* src = "./vsrc/ps2_keyboard.v:28" *)
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\rom"),
    .PRIORITY(32'd117),
    .WIDTH(32'd8),
    .WORDS(32'd1)
  ) _1250_ (
    .ADDR(32'd43),
    .DATA(8'h46)
  );
  (* src = "./vsrc/ps2_keyboard.v:29" *)
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\rom"),
    .PRIORITY(32'd118),
    .WIDTH(32'd8),
    .WORDS(32'd1)
  ) _1251_ (
    .ADDR(32'd52),
    .DATA(8'h47)
  );
  (* src = "./vsrc/ps2_keyboard.v:30" *)
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\rom"),
    .PRIORITY(32'd119),
    .WIDTH(32'd8),
    .WORDS(32'd1)
  ) _1252_ (
    .ADDR(32'd51),
    .DATA(8'h48)
  );
  (* src = "./vsrc/ps2_keyboard.v:31" *)
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\rom"),
    .PRIORITY(32'd120),
    .WIDTH(32'd8),
    .WORDS(32'd1)
  ) _1253_ (
    .ADDR(32'd67),
    .DATA(8'h49)
  );
  (* src = "./vsrc/ps2_keyboard.v:32" *)
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\rom"),
    .PRIORITY(32'd121),
    .WIDTH(32'd8),
    .WORDS(32'd1)
  ) _1254_ (
    .ADDR(32'd59),
    .DATA(8'h4a)
  );
  (* src = "./vsrc/ps2_keyboard.v:33" *)
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\rom"),
    .PRIORITY(32'd122),
    .WIDTH(32'd8),
    .WORDS(32'd1)
  ) _1255_ (
    .ADDR(32'd66),
    .DATA(8'h4b)
  );
  (* src = "./vsrc/ps2_keyboard.v:34" *)
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\rom"),
    .PRIORITY(32'd123),
    .WIDTH(32'd8),
    .WORDS(32'd1)
  ) _1256_ (
    .ADDR(32'd75),
    .DATA(8'h4c)
  );
  (* src = "./vsrc/ps2_keyboard.v:35" *)
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\rom"),
    .PRIORITY(32'd124),
    .WIDTH(32'd8),
    .WORDS(32'd1)
  ) _1257_ (
    .ADDR(32'd58),
    .DATA(8'h4d)
  );
  (* src = "./vsrc/ps2_keyboard.v:36" *)
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\rom"),
    .PRIORITY(32'd125),
    .WIDTH(32'd8),
    .WORDS(32'd1)
  ) _1258_ (
    .ADDR(32'd49),
    .DATA(8'h4e)
  );
  (* src = "./vsrc/ps2_keyboard.v:37" *)
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\rom"),
    .PRIORITY(32'd126),
    .WIDTH(32'd8),
    .WORDS(32'd1)
  ) _1259_ (
    .ADDR(32'd68),
    .DATA(8'h4f)
  );
  (* src = "./vsrc/ps2_keyboard.v:38" *)
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\rom"),
    .PRIORITY(32'd127),
    .WIDTH(32'd8),
    .WORDS(32'd1)
  ) _1260_ (
    .ADDR(32'd77),
    .DATA(8'h50)
  );
  (* src = "./vsrc/ps2_keyboard.v:39" *)
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\rom"),
    .PRIORITY(32'd128),
    .WIDTH(32'd8),
    .WORDS(32'd1)
  ) _1261_ (
    .ADDR(32'd21),
    .DATA(8'h51)
  );
  (* src = "./vsrc/ps2_keyboard.v:40" *)
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\rom"),
    .PRIORITY(32'd129),
    .WIDTH(32'd8),
    .WORDS(32'd1)
  ) _1262_ (
    .ADDR(32'd45),
    .DATA(8'h52)
  );
  (* src = "./vsrc/ps2_keyboard.v:41" *)
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\rom"),
    .PRIORITY(32'd130),
    .WIDTH(32'd8),
    .WORDS(32'd1)
  ) _1263_ (
    .ADDR(32'd27),
    .DATA(8'h53)
  );
  (* src = "./vsrc/ps2_keyboard.v:42" *)
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\rom"),
    .PRIORITY(32'd131),
    .WIDTH(32'd8),
    .WORDS(32'd1)
  ) _1264_ (
    .ADDR(32'd44),
    .DATA(8'h54)
  );
  (* src = "./vsrc/ps2_keyboard.v:43" *)
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\rom"),
    .PRIORITY(32'd132),
    .WIDTH(32'd8),
    .WORDS(32'd1)
  ) _1265_ (
    .ADDR(32'd60),
    .DATA(8'h55)
  );
  (* src = "./vsrc/ps2_keyboard.v:44" *)
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\rom"),
    .PRIORITY(32'd133),
    .WIDTH(32'd8),
    .WORDS(32'd1)
  ) _1266_ (
    .ADDR(32'd42),
    .DATA(8'h56)
  );
  (* src = "./vsrc/ps2_keyboard.v:45" *)
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\rom"),
    .PRIORITY(32'd134),
    .WIDTH(32'd8),
    .WORDS(32'd1)
  ) _1267_ (
    .ADDR(32'd29),
    .DATA(8'h57)
  );
  (* src = "./vsrc/ps2_keyboard.v:46" *)
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\rom"),
    .PRIORITY(32'd135),
    .WIDTH(32'd8),
    .WORDS(32'd1)
  ) _1268_ (
    .ADDR(32'd34),
    .DATA(8'h58)
  );
  (* src = "./vsrc/ps2_keyboard.v:47" *)
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\rom"),
    .PRIORITY(32'd136),
    .WIDTH(32'd8),
    .WORDS(32'd1)
  ) _1269_ (
    .ADDR(32'd53),
    .DATA(8'h59)
  );
  (* src = "./vsrc/ps2_keyboard.v:48" *)
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\rom"),
    .PRIORITY(32'd137),
    .WIDTH(32'd8),
    .WORDS(32'd1)
  ) _1270_ (
    .ADDR(32'd26),
    .DATA(8'h5a)
  );
  (* src = "./vsrc/ps2_keyboard.v:50" *)
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\rom"),
    .PRIORITY(32'd138),
    .WIDTH(32'd8),
    .WORDS(32'd1)
  ) _1271_ (
    .ADDR(32'd69),
    .DATA(8'h30)
  );
  (* src = "./vsrc/ps2_keyboard.v:51" *)
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\rom"),
    .PRIORITY(32'd139),
    .WIDTH(32'd8),
    .WORDS(32'd1)
  ) _1272_ (
    .ADDR(32'd22),
    .DATA(8'h31)
  );
  (* src = "./vsrc/ps2_keyboard.v:52" *)
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\rom"),
    .PRIORITY(32'd140),
    .WIDTH(32'd8),
    .WORDS(32'd1)
  ) _1273_ (
    .ADDR(32'd30),
    .DATA(8'h32)
  );
  (* src = "./vsrc/ps2_keyboard.v:53" *)
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\rom"),
    .PRIORITY(32'd141),
    .WIDTH(32'd8),
    .WORDS(32'd1)
  ) _1274_ (
    .ADDR(32'd38),
    .DATA(8'h33)
  );
  (* src = "./vsrc/ps2_keyboard.v:54" *)
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\rom"),
    .PRIORITY(32'd142),
    .WIDTH(32'd8),
    .WORDS(32'd1)
  ) _1275_ (
    .ADDR(32'd37),
    .DATA(8'h34)
  );
  (* src = "./vsrc/ps2_keyboard.v:55" *)
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\rom"),
    .PRIORITY(32'd143),
    .WIDTH(32'd8),
    .WORDS(32'd1)
  ) _1276_ (
    .ADDR(32'd46),
    .DATA(8'h35)
  );
  (* src = "./vsrc/ps2_keyboard.v:56" *)
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\rom"),
    .PRIORITY(32'd144),
    .WIDTH(32'd8),
    .WORDS(32'd1)
  ) _1277_ (
    .ADDR(32'd54),
    .DATA(8'h36)
  );
  (* src = "./vsrc/ps2_keyboard.v:57" *)
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\rom"),
    .PRIORITY(32'd145),
    .WIDTH(32'd8),
    .WORDS(32'd1)
  ) _1278_ (
    .ADDR(32'd61),
    .DATA(8'h37)
  );
  (* src = "./vsrc/ps2_keyboard.v:58" *)
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\rom"),
    .PRIORITY(32'd146),
    .WIDTH(32'd8),
    .WORDS(32'd1)
  ) _1279_ (
    .ADDR(32'd62),
    .DATA(8'h38)
  );
  (* src = "./vsrc/ps2_keyboard.v:59" *)
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\rom"),
    .PRIORITY(32'd147),
    .WIDTH(32'd8),
    .WORDS(32'd1)
  ) _1280_ (
    .ADDR(32'd70),
    .DATA(8'h39)
  );
  (* src = "./vsrc/ps2_keyboard.v:90" *)
  \$memrd  #(
    .ABITS(32'd8),
    .CLK_ENABLE(32'd0),
    .CLK_POLARITY(32'd0),
    .MEMID("\\rom"),
    .TRANSPARENT(32'd0),
    .WIDTH(32'd8)
  ) _1281_ (
    .ADDR(buffer[8:1]),
    .CLK(1'hx),
    .DATA(_0513_),
    .EN(1'hx)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./vsrc/ps2_keyboard.v:129" *)
  ps2_seg show0 (
    .bin_in(bin_in0),
    .check(off),
    .seg_out(seg0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./vsrc/ps2_keyboard.v:130" *)
  ps2_seg show1 (
    .bin_in(bin_in1),
    .check(off),
    .seg_out(seg1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./vsrc/ps2_keyboard.v:131" *)
  ps2_seg show2 (
    .bin_in(bin_in2),
    .check(off),
    .seg_out(seg2)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./vsrc/ps2_keyboard.v:132" *)
  ps2_seg show3 (
    .bin_in(bin_in3),
    .check(off),
    .seg_out(seg3)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./vsrc/ps2_keyboard.v:133" *)
  seg16 show4 (
    .bin_in(bin_in4),
    .seg_out(seg4)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./vsrc/ps2_keyboard.v:134" *)
  seg16 show5 (
    .bin_in(bin_in5),
    .seg_out(seg5)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./vsrc/ps2_keyboard.v:135" *)
  ps2_seg show6 (
    .bin_in(4'h0),
    .check(1'h1),
    .seg_out(seg6)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./vsrc/ps2_keyboard.v:136" *)
  ps2_seg show7 (
    .bin_in(4'h0),
    .check(1'h1),
    .seg_out(seg7)
  );
  assign kill = 1'h1;
  assign _0512_ = _0666_;
  assign _0645_ = _0646_;
  assign _0648_ = _0796_;
  assign _0664_ = _0797_;
  assign _0643_ = _0798_[7:0];
  assign _0622_ = _0623_;
  assign _0625_ = _0681_;
  assign _0641_ = _0682_;
  assign _0452_ = _0683_[31:0];
  assign _0600_ = _0601_;
  assign _0603_ = _0669_;
  assign _0619_ = _0670_;
  assign _0448_ = _0671_[3:0];
  assign _0659_ = 1024'h000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000070726f633b206f7074202d66617374;
  assign _0660_ = _0665_;
  assign _0663_[0] = _0664_[0];
  assign _0662_ = 32'd8;
  assign _0661_ = 32'd0;
  assign _0650_ = 8'hff;
  assign _0646_ = press_count;
  assign _0636_ = 1024'h000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000070726f633b206f7074202d66617374;
  assign _0637_ = _0642_;
  assign _0640_[0] = _0641_[0];
  assign _0639_ = 32'd32;
  assign _0638_ = 32'd0;
  assign _0627_ = 32'd1;
  assign _0623_ = { 24'h000000, press_count };
  assign _0614_ = 1024'h000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000070726f633b206f7074202d66617374;
  assign _0615_ = _0620_;
  assign _0618_[0] = _0619_[0];
  assign _0617_ = 32'd4;
  assign _0616_ = 32'd0;
  assign _0605_ = count;
  assign _0601_ = 4'h1;
  assign _0096_ = count[2];
  assign _0095_ = count[1];
  assign _0094_ = count[0];
  assign _0440_ = press_count[7];
  assign _0439_ = press_count[6];
  assign _0438_ = press_count[5];
  assign _0437_ = press_count[4];
  assign _0436_ = press_count[3];
  assign _0435_ = press_count[2];
  assign _0434_ = press_count[1];
  assign _0433_ = press_count[0];
  assign _0097_ = count[3];
  assign _0061_ = bin_in0[2];
  assign _0060_ = bin_in0[1];
  assign _0059_ = bin_in0[0];
  assign _0444_ = rst;
  assign _0000_[2] = _0013_;
  assign _0000_[1] = _0012_;
  assign _0000_[0] = _0011_;
  assign _0010_[6] = _0057_;
  assign _0010_[5] = _0056_;
  assign _0010_[4] = _0055_;
  assign _0010_[3] = _0054_;
  assign _0010_[2] = _0053_;
  assign _0010_[1] = _0052_;
  assign _0010_[0] = _0051_;
  assign _0008_[2] = _0048_;
  assign _0008_[1] = _0047_;
  assign _0008_[0] = _0046_;
  assign _0077_ = bin_in4[2];
  assign _0076_ = bin_in4[1];
  assign _0075_ = bin_in4[0];
  assign _0004_[2] = _0029_;
  assign _0004_[1] = _0028_;
  assign _0004_[0] = _0027_;
  assign _0073_ = bin_in3[2];
  assign _0072_ = bin_in3[1];
  assign _0071_ = bin_in3[0];
  assign _0104_ = _0513_[6];
  assign _0093_ = check;
  assign _0103_ = _0513_[5];
  assign _0102_ = _0513_[4];
  assign _0065_ = bin_in1[2];
  assign _0064_ = bin_in1[1];
  assign _0063_ = bin_in1[0];
  assign _0001_[2] = _0017_;
  assign _0001_[1] = _0016_;
  assign _0001_[0] = _0015_;
  assign _0086_ = buffer[3];
  assign _0085_ = buffer[2];
  assign _0084_ = buffer[1];
  assign _0003_[2] = _0025_;
  assign _0003_[1] = _0024_;
  assign _0003_[0] = _0023_;
  assign _0069_ = bin_in2[2];
  assign _0068_ = bin_in2[1];
  assign _0067_ = bin_in2[0];
  assign _0100_ = _0513_[2];
  assign _0099_ = _0513_[1];
  assign _0098_ = _0513_[0];
  assign _0002_[2] = _0021_;
  assign _0002_[1] = _0020_;
  assign _0002_[0] = _0019_;
  assign _0090_ = buffer[7];
  assign _0089_ = buffer[6];
  assign _0088_ = buffer[5];
  assign _0087_ = buffer[4];
  assign _0091_ = buffer[8];
  assign _0081_ = bin_in5[2];
  assign _0080_ = bin_in5[1];
  assign _0079_ = bin_in5[0];
  assign _0005_[2] = _0033_;
  assign _0005_[1] = _0032_;
  assign _0005_[0] = _0031_;
  assign _0442_ = ps2_clk_sync[2];
  assign _0083_ = buffer[0];
  assign _0443_ = ps2_data;
  assign _0441_ = ps2_clk_sync[1];
  assign _0092_ = buffer[9];
  assign _0006_[9] = _0044_;
  assign _0006_[8] = _0043_;
  assign _0006_[7] = _0042_;
  assign _0006_[6] = _0041_;
  assign _0006_[5] = _0040_;
  assign _0006_[4] = _0039_;
  assign _0006_[3] = _0038_;
  assign _0006_[2] = _0037_;
  assign _0006_[1] = _0036_;
  assign _0006_[0] = _0035_;
  assign _0432_ = off;
  assign _0009_ = _0050_;
  assign _0007_ = _0045_;
  assign _0082_ = bin_in5[3];
  assign _0005_[3] = _0034_;
  assign _0078_ = bin_in4[3];
  assign _0004_[3] = _0030_;
  assign _0105_ = _0513_[7];
  assign _0074_ = bin_in3[3];
  assign _0003_[3] = _0026_;
  assign _0101_ = _0513_[3];
  assign _0070_ = bin_in2[3];
  assign _0002_[3] = _0022_;
  assign _0066_ = bin_in1[3];
  assign _0001_[3] = _0018_;
  assign _0062_ = bin_in0[3];
  assign _0000_[3] = _0014_;
  assign _0010_[7] = _0058_;
  assign _0008_[3] = _0049_;
endmodule

(* src = "./vsrc/ps2_seg.v:1" *)
module ps2_seg(bin_in, check, seg_out);
  (* src = "./vsrc/ps2_seg.v:6" *)
  reg [7:0] _0_;
  (* src = "./vsrc/ps2_seg.v:6" *)
  reg [7:0] _1_;
  (* src = "./vsrc/ps2_seg.v:6" *)
  reg [7:0] _2_;
  (* src = "./vsrc/ps2_seg.v:7" *)
  wire _3_;
  (* src = "./vsrc/ps2_seg.v:2" *)
  input [3:0] bin_in;
  (* src = "./vsrc/ps2_seg.v:3" *)
  input check;
  (* src = "./vsrc/ps2_seg.v:4" *)
  output [7:0] seg_out;
  reg [7:0] seg_out;
  assign _3_ = check == (* src = "./vsrc/ps2_seg.v:7" *) 32'd1;
  always @* begin
    _0_ = _1_;
    (* src = "./vsrc/ps2_seg.v:7" *)
    casez (_3_)
      /* src = "./vsrc/ps2_seg.v:7" */
      1'h1:
        begin
          _1_ = 8'hff;
        end
      /* src = "./vsrc/ps2_seg.v:10" */
      default:
        begin
          _1_ = _2_;
          (* src = "./vsrc/ps2_seg.v:11" *)
          casez (bin_in)
            /* src = "./vsrc/ps2_seg.v:12" */
            4'h0:
              begin
                _2_ = 8'h03;
              end
            /* src = "./vsrc/ps2_seg.v:13" */
            4'h1:
              begin
                _2_ = 8'h9f;
              end
            /* src = "./vsrc/ps2_seg.v:14" */
            4'h2:
              begin
                _2_ = 8'h25;
              end
            /* src = "./vsrc/ps2_seg.v:15" */
            4'h3:
              begin
                _2_ = 8'h0d;
              end
            /* src = "./vsrc/ps2_seg.v:16" */
            4'h4:
              begin
                _2_ = 8'h99;
              end
            /* src = "./vsrc/ps2_seg.v:17" */
            4'h5:
              begin
                _2_ = 8'h49;
              end
            /* src = "./vsrc/ps2_seg.v:18" */
            4'h6:
              begin
                _2_ = 8'h41;
              end
            /* src = "./vsrc/ps2_seg.v:19" */
            4'h7:
              begin
                _2_ = 8'h1f;
              end
            /* src = "./vsrc/ps2_seg.v:20" */
            4'h8:
              begin
                _2_ = 8'h01;
              end
            /* src = "./vsrc/ps2_seg.v:21" */
            4'h9:
              begin
                _2_ = 8'h09;
              end
            /* src = "./vsrc/ps2_seg.v:22" */
            4'ha:
              begin
                _2_ = 8'h11;
              end
            /* src = "./vsrc/ps2_seg.v:23" */
            4'hb:
              begin
                _2_ = 8'hc1;
              end
            /* src = "./vsrc/ps2_seg.v:24" */
            4'hc:
              begin
                _2_ = 8'h63;
              end
            /* src = "./vsrc/ps2_seg.v:25" */
            4'hd:
              begin
                _2_ = 8'h85;
              end
            /* src = "./vsrc/ps2_seg.v:26" */
            4'he:
              begin
                _2_ = 8'h61;
              end
            /* src = "./vsrc/ps2_seg.v:27" */
            4'hf:
              begin
                _2_ = 8'h71;
              end
            /* src = "./vsrc/ps2_seg.v:28" */
            default:
              begin
                _2_ = 8'hff;
              end
          endcase
        end
    endcase
  end
  always @* begin
      seg_out <= _0_;
  end
endmodule

(* src = "./vsrc/seg16.v:1" *)
module seg16(bin_in, seg_out);
  (* src = "./vsrc/seg16.v:5" *)
  reg [7:0] _0_;
  (* src = "./vsrc/seg16.v:5" *)
  reg [7:0] _1_;
  (* src = "./vsrc/seg16.v:2" *)
  input [3:0] bin_in;
  (* src = "./vsrc/seg16.v:3" *)
  output [7:0] seg_out;
  reg [7:0] seg_out;
  always @* begin
    _0_ = _1_;
    (* src = "./vsrc/seg16.v:6" *)
    casez (bin_in)
      /* src = "./vsrc/seg16.v:7" */
      4'h0:
        begin
          _1_ = 8'h03;
        end
      /* src = "./vsrc/seg16.v:8" */
      4'h1:
        begin
          _1_ = 8'h9f;
        end
      /* src = "./vsrc/seg16.v:9" */
      4'h2:
        begin
          _1_ = 8'h25;
        end
      /* src = "./vsrc/seg16.v:10" */
      4'h3:
        begin
          _1_ = 8'h0d;
        end
      /* src = "./vsrc/seg16.v:11" */
      4'h4:
        begin
          _1_ = 8'h99;
        end
      /* src = "./vsrc/seg16.v:12" */
      4'h5:
        begin
          _1_ = 8'h49;
        end
      /* src = "./vsrc/seg16.v:13" */
      4'h6:
        begin
          _1_ = 8'h41;
        end
      /* src = "./vsrc/seg16.v:14" */
      4'h7:
        begin
          _1_ = 8'h1f;
        end
      /* src = "./vsrc/seg16.v:15" */
      4'h8:
        begin
          _1_ = 8'h01;
        end
      /* src = "./vsrc/seg16.v:16" */
      4'h9:
        begin
          _1_ = 8'h09;
        end
      /* src = "./vsrc/seg16.v:17" */
      4'ha:
        begin
          _1_ = 8'h11;
        end
      /* src = "./vsrc/seg16.v:18" */
      4'hb:
        begin
          _1_ = 8'hc1;
        end
      /* src = "./vsrc/seg16.v:19" */
      4'hc:
        begin
          _1_ = 8'h63;
        end
      /* src = "./vsrc/seg16.v:20" */
      4'hd:
        begin
          _1_ = 8'h85;
        end
      /* src = "./vsrc/seg16.v:21" */
      4'he:
        begin
          _1_ = 8'h61;
        end
      /* src = "./vsrc/seg16.v:22" */
      4'hf:
        begin
          _1_ = 8'h71;
        end
      /* src = "./vsrc/seg16.v:23" */
      default:
        begin
          _1_ = 8'hff;
        end
    endcase
  end
  always @* begin
      seg_out <= _0_;
  end
endmodule
