// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "Vrv32e__Syms.h"


VL_ATTR_COLD void Vrv32e___024root__trace_init_sub__TOP__0(Vrv32e___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vrv32e__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vrv32e___024root__trace_init_sub__TOP__0\n"); );
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBit(c+183,"clk", false,-1);
    tracep->declBit(c+184,"reset", false,-1);
    tracep->pushNamePrefix("rv32e ");
    tracep->declBit(c+183,"clk", false,-1);
    tracep->declBit(c+184,"reset", false,-1);
    tracep->declBus(c+40,"pc", false,-1, 31,0);
    tracep->declBus(c+41,"instr", false,-1, 31,0);
    tracep->declBit(c+42,"if_ready", false,-1);
    tracep->declBit(c+43,"wb_valid", false,-1);
    tracep->declBit(c+44,"if_valid", false,-1);
    tracep->declBit(c+45,"id_ready", false,-1);
    tracep->declBit(c+46,"if_access_fault", false,-1);
    tracep->declBus(c+47,"if_fault_addr", false,-1, 31,0);
    tracep->declBus(c+185,"trap_pc", false,-1, 31,0);
    tracep->declBus(c+48,"ifu_sram_araddr", false,-1, 31,0);
    tracep->declBit(c+49,"ifu_sram_arvalid", false,-1);
    tracep->declBit(c+150,"ifu_sram_arready", false,-1);
    tracep->declBus(c+151,"ifu_sram_rdata", false,-1, 31,0);
    tracep->declBit(c+152,"ifu_sram_rvalid", false,-1);
    tracep->declBit(c+50,"ifu_sram_rready", false,-1);
    tracep->declBus(c+153,"ifu_sram_rresp", false,-1, 1,0);
    tracep->declBus(c+1,"ifu_sram_awaddr", false,-1, 31,0);
    tracep->declBit(c+2,"ifu_sram_awvalid", false,-1);
    tracep->declBit(c+186,"ifu_sram_awready", false,-1);
    tracep->declBus(c+3,"ifu_sram_wdata", false,-1, 31,0);
    tracep->declBus(c+4,"ifu_sram_wstrb", false,-1, 3,0);
    tracep->declBit(c+5,"ifu_sram_wvalid", false,-1);
    tracep->declBit(c+187,"ifu_sram_wready", false,-1);
    tracep->declBus(c+188,"ifu_sram_bresp", false,-1, 1,0);
    tracep->declBit(c+189,"ifu_sram_bvalid", false,-1);
    tracep->declBit(c+6,"ifu_sram_bready", false,-1);
    tracep->declBus(c+51,"opcode", false,-1, 6,0);
    tracep->declBus(c+52,"rs1", false,-1, 4,0);
    tracep->declBus(c+53,"rs2", false,-1, 4,0);
    tracep->declBus(c+54,"rd", false,-1, 4,0);
    tracep->declBus(c+55,"imm", false,-1, 31,0);
    tracep->declBus(c+56,"func3", false,-1, 2,0);
    tracep->declBus(c+57,"func7", false,-1, 6,0);
    tracep->declBit(c+58,"RegWrite", false,-1);
    tracep->declBit(c+59,"MemWrite", false,-1);
    tracep->declBit(c+60,"MemRead", false,-1);
    tracep->declBus(c+61,"alu_op", false,-1, 3,0);
    tracep->declBus(c+62,"MemLen", false,-1, 2,0);
    tracep->declBit(c+63,"id_valid", false,-1);
    tracep->declBit(c+64,"ex_ready", false,-1);
    tracep->declBit(c+190,"reg_valid", false,-1);
    tracep->declBit(c+191,"reg_ready", false,-1);
    tracep->declBus(c+65,"rs1_val", false,-1, 31,0);
    tracep->declBus(c+66,"rs2_val", false,-1, 31,0);
    tracep->declBus(c+67,"alu_result", false,-1, 31,0);
    tracep->declBit(c+68,"alu_zero", false,-1);
    tracep->declBit(c+69,"alu_less", false,-1);
    tracep->declBit(c+70,"ex_valid", false,-1);
    tracep->declBit(c+71,"mem_ready", false,-1);
    tracep->declBus(c+72,"data_out", false,-1, 31,0);
    tracep->declBit(c+73,"mem_valid", false,-1);
    tracep->declBit(c+74,"wb_ready", false,-1);
    tracep->declBit(c+75,"load_access_fault", false,-1);
    tracep->declBit(c+76,"store_access_fault", false,-1);
    tracep->declBus(c+77,"mem_fault_addr", false,-1, 31,0);
    tracep->declBus(c+78,"mem_sram_araddr", false,-1, 31,0);
    tracep->declBit(c+79,"mem_sram_arvalid", false,-1);
    tracep->declBit(c+154,"mem_sram_arready", false,-1);
    tracep->declBus(c+155,"mem_sram_rdata", false,-1, 31,0);
    tracep->declBit(c+156,"mem_sram_rvalid", false,-1);
    tracep->declBit(c+80,"mem_sram_rready", false,-1);
    tracep->declBus(c+157,"mem_sram_rresp", false,-1, 1,0);
    tracep->declBus(c+81,"mem_sram_awaddr", false,-1, 31,0);
    tracep->declBit(c+82,"mem_sram_awvalid", false,-1);
    tracep->declBit(c+158,"mem_sram_awready", false,-1);
    tracep->declBus(c+83,"mem_sram_wdata", false,-1, 31,0);
    tracep->declBus(c+84,"mem_sram_wstrb", false,-1, 3,0);
    tracep->declBit(c+85,"mem_sram_wvalid", false,-1);
    tracep->declBit(c+159,"mem_sram_wready", false,-1);
    tracep->declBus(c+160,"mem_sram_bresp", false,-1, 1,0);
    tracep->declBit(c+161,"mem_sram_bvalid", false,-1);
    tracep->declBit(c+86,"mem_sram_bready", false,-1);
    tracep->declBus(c+87,"wb_data", false,-1, 31,0);
    tracep->declBus(c+88,"jal_target", false,-1, 31,0);
    tracep->declBus(c+89,"jalr_target", false,-1, 31,0);
    tracep->declBit(c+90,"is_jal", false,-1);
    tracep->declBit(c+91,"is_jalr", false,-1);
    tracep->declBit(c+92,"take_branch", false,-1);
    tracep->declBus(c+93,"branch_target", false,-1, 31,0);
    tracep->declBus(c+192,"rd_wb", false,-1, 4,0);
    tracep->declBit(c+193,"RegWrite_wb", false,-1);
    tracep->declBit(c+194,"wb_MemRead", false,-1);
    tracep->declBit(c+195,"wb_MemWrite", false,-1);
    tracep->declBus(c+196,"wb_MemLen", false,-1, 2,0);
    tracep->declBus(c+197,"wb_addr", false,-1, 31,0);
    tracep->declBus(c+198,"wb_data_in", false,-1, 31,0);
    tracep->declBus(c+162,"sram_araddr", false,-1, 31,0);
    tracep->declBit(c+163,"sram_arvalid", false,-1);
    tracep->declBit(c+7,"sram_arready", false,-1);
    tracep->declBus(c+8,"sram_rresp", false,-1, 1,0);
    tracep->declBus(c+9,"sram_rdata", false,-1, 31,0);
    tracep->declBit(c+10,"sram_rvalid", false,-1);
    tracep->declBit(c+164,"sram_rready", false,-1);
    tracep->declBus(c+165,"sram_awaddr", false,-1, 31,0);
    tracep->declBit(c+11,"sram_awready", false,-1);
    tracep->declBit(c+166,"sram_awvalid", false,-1);
    tracep->declBus(c+167,"sram_wdata", false,-1, 31,0);
    tracep->declBus(c+168,"sram_wstrb", false,-1, 3,0);
    tracep->declBit(c+169,"sram_wvalid", false,-1);
    tracep->declBit(c+12,"sram_wready", false,-1);
    tracep->declBus(c+13,"sram_bresp", false,-1, 1,0);
    tracep->declBit(c+14,"sram_bvalid", false,-1);
    tracep->declBit(c+170,"sram_bready", false,-1);
    tracep->declBus(c+171,"uart_araddr", false,-1, 31,0);
    tracep->declBit(c+172,"uart_arvalid", false,-1);
    tracep->declBit(c+15,"uart_arready", false,-1);
    tracep->declBus(c+16,"uart_rresp", false,-1, 1,0);
    tracep->declBus(c+17,"uart_rdata", false,-1, 31,0);
    tracep->declBit(c+18,"uart_rvalid", false,-1);
    tracep->declBit(c+173,"uart_rready", false,-1);
    tracep->declBus(c+174,"uart_awaddr", false,-1, 31,0);
    tracep->declBit(c+19,"uart_awready", false,-1);
    tracep->declBit(c+175,"uart_awvalid", false,-1);
    tracep->declBus(c+176,"uart_wdata", false,-1, 31,0);
    tracep->declBus(c+177,"uart_wstrb", false,-1, 3,0);
    tracep->declBit(c+178,"uart_wvalid", false,-1);
    tracep->declBit(c+20,"uart_wready", false,-1);
    tracep->declBus(c+21,"uart_bresp", false,-1, 1,0);
    tracep->declBit(c+22,"uart_bvalid", false,-1);
    tracep->declBit(c+179,"uart_bready", false,-1);
    tracep->pushNamePrefix("axi_arb ");
    tracep->declBit(c+183,"clk", false,-1);
    tracep->declBit(c+184,"reset", false,-1);
    tracep->declBus(c+48,"ifu_araddr", false,-1, 31,0);
    tracep->declBit(c+49,"ifu_arvalid", false,-1);
    tracep->declBit(c+150,"ifu_arready", false,-1);
    tracep->declBus(c+151,"ifu_rdata", false,-1, 31,0);
    tracep->declBus(c+153,"ifu_rresp", false,-1, 1,0);
    tracep->declBit(c+152,"ifu_rvalid", false,-1);
    tracep->declBit(c+50,"ifu_rready", false,-1);
    tracep->declBus(c+78,"mem_araddr", false,-1, 31,0);
    tracep->declBit(c+79,"mem_arvalid", false,-1);
    tracep->declBit(c+154,"mem_arready", false,-1);
    tracep->declBus(c+155,"mem_rdata", false,-1, 31,0);
    tracep->declBus(c+157,"mem_rresp", false,-1, 1,0);
    tracep->declBit(c+156,"mem_rvalid", false,-1);
    tracep->declBit(c+80,"mem_rready", false,-1);
    tracep->declBus(c+81,"mem_awaddr", false,-1, 31,0);
    tracep->declBit(c+82,"mem_awvalid", false,-1);
    tracep->declBit(c+158,"mem_awready", false,-1);
    tracep->declBus(c+83,"mem_wdata", false,-1, 31,0);
    tracep->declBus(c+84,"mem_wstrb", false,-1, 3,0);
    tracep->declBit(c+85,"mem_wvalid", false,-1);
    tracep->declBit(c+159,"mem_wready", false,-1);
    tracep->declBus(c+160,"mem_bresp", false,-1, 1,0);
    tracep->declBit(c+161,"mem_bvalid", false,-1);
    tracep->declBit(c+86,"mem_bready", false,-1);
    tracep->declBus(c+171,"uart_araddr", false,-1, 31,0);
    tracep->declBit(c+172,"uart_arvalid", false,-1);
    tracep->declBit(c+15,"uart_arready", false,-1);
    tracep->declBus(c+17,"uart_rdata", false,-1, 31,0);
    tracep->declBus(c+16,"uart_rresp", false,-1, 1,0);
    tracep->declBit(c+18,"uart_rvalid", false,-1);
    tracep->declBit(c+173,"uart_rready", false,-1);
    tracep->declBus(c+174,"uart_awaddr", false,-1, 31,0);
    tracep->declBit(c+175,"uart_awvalid", false,-1);
    tracep->declBit(c+19,"uart_awready", false,-1);
    tracep->declBus(c+176,"uart_wdata", false,-1, 31,0);
    tracep->declBus(c+177,"uart_wstrb", false,-1, 3,0);
    tracep->declBit(c+178,"uart_wvalid", false,-1);
    tracep->declBit(c+20,"uart_wready", false,-1);
    tracep->declBus(c+21,"uart_bresp", false,-1, 1,0);
    tracep->declBit(c+22,"uart_bvalid", false,-1);
    tracep->declBit(c+179,"uart_bready", false,-1);
    tracep->declBus(c+162,"sram_araddr", false,-1, 31,0);
    tracep->declBit(c+163,"sram_arvalid", false,-1);
    tracep->declBit(c+7,"sram_arready", false,-1);
    tracep->declBus(c+9,"sram_rdata", false,-1, 31,0);
    tracep->declBus(c+8,"sram_rresp", false,-1, 1,0);
    tracep->declBit(c+10,"sram_rvalid", false,-1);
    tracep->declBit(c+164,"sram_rready", false,-1);
    tracep->declBus(c+165,"sram_awaddr", false,-1, 31,0);
    tracep->declBit(c+166,"sram_awvalid", false,-1);
    tracep->declBit(c+11,"sram_awready", false,-1);
    tracep->declBus(c+167,"sram_wdata", false,-1, 31,0);
    tracep->declBus(c+168,"sram_wstrb", false,-1, 3,0);
    tracep->declBit(c+169,"sram_wvalid", false,-1);
    tracep->declBit(c+12,"sram_wready", false,-1);
    tracep->declBus(c+13,"sram_bresp", false,-1, 1,0);
    tracep->declBit(c+14,"sram_bvalid", false,-1);
    tracep->declBit(c+170,"sram_bready", false,-1);
    tracep->declBus(c+199,"NONE", false,-1, 2,0);
    tracep->declBus(c+200,"IFU", false,-1, 2,0);
    tracep->declBus(c+201,"MEM_READ", false,-1, 2,0);
    tracep->declBus(c+202,"MEM_WRITE", false,-1, 2,0);
    tracep->declBus(c+203,"ERROR", false,-1, 2,0);
    tracep->declBus(c+204,"SRAM", false,-1, 1,0);
    tracep->declBus(c+205,"UART", false,-1, 1,0);
    tracep->declBus(c+206,"ERR", false,-1, 1,0);
    tracep->declBus(c+23,"current_master", false,-1, 2,0);
    tracep->declBus(c+180,"next_master", false,-1, 2,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("ex_stage ");
    tracep->declBit(c+183,"clk", false,-1);
    tracep->declBit(c+184,"reset", false,-1);
    tracep->declBit(c+63,"id_valid", false,-1);
    tracep->declBit(c+64,"ex_ready", false,-1);
    tracep->declBus(c+51,"opcode", false,-1, 6,0);
    tracep->declBus(c+65,"rs1_val", false,-1, 31,0);
    tracep->declBus(c+66,"rs2_val", false,-1, 31,0);
    tracep->declBus(c+55,"imm", false,-1, 31,0);
    tracep->declBus(c+61,"alu_op", false,-1, 3,0);
    tracep->declBit(c+71,"mem_ready", false,-1);
    tracep->declBit(c+70,"ex_valid", false,-1);
    tracep->declBus(c+67,"alu_result", false,-1, 31,0);
    tracep->declBit(c+68,"alu_zero", false,-1);
    tracep->declBit(c+69,"alu_less", false,-1);
    tracep->declBus(c+94,"state", false,-1, 31,0);
    tracep->declBus(c+95,"next_state", false,-1, 31,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("id_stage ");
    tracep->declBit(c+183,"clk", false,-1);
    tracep->declBit(c+184,"reset", false,-1);
    tracep->declBus(c+41,"instr", false,-1, 31,0);
    tracep->declBit(c+64,"ex_ready", false,-1);
    tracep->declBit(c+44,"if_valid", false,-1);
    tracep->declBit(c+45,"id_ready", false,-1);
    tracep->declBit(c+63,"id_valid", false,-1);
    tracep->declBus(c+51,"opcode", false,-1, 6,0);
    tracep->declBus(c+52,"rs1", false,-1, 4,0);
    tracep->declBus(c+53,"rs2", false,-1, 4,0);
    tracep->declBus(c+54,"rd", false,-1, 4,0);
    tracep->declBus(c+55,"imm", false,-1, 31,0);
    tracep->declBus(c+56,"func3", false,-1, 2,0);
    tracep->declBus(c+57,"func7", false,-1, 6,0);
    tracep->declBit(c+58,"RegWrite", false,-1);
    tracep->declBit(c+59,"MemWrite", false,-1);
    tracep->declBit(c+60,"MemRead", false,-1);
    tracep->declBus(c+61,"alu_op", false,-1, 3,0);
    tracep->declBus(c+62,"MemLen", false,-1, 2,0);
    tracep->declBus(c+96,"state", false,-1, 31,0);
    tracep->declBus(c+97,"next_state", false,-1, 31,0);
    tracep->declBus(c+98,"immI", false,-1, 31,0);
    tracep->declBus(c+99,"immU", false,-1, 31,0);
    tracep->declBus(c+100,"immS", false,-1, 31,0);
    tracep->declBus(c+101,"immB", false,-1, 31,0);
    tracep->declBus(c+102,"immJ", false,-1, 31,0);
    tracep->declBus(c+207,"immR", false,-1, 31,0);
    tracep->declBus(c+103,"get_opcode", false,-1, 4,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("if_stage ");
    tracep->declBit(c+183,"clk", false,-1);
    tracep->declBit(c+184,"reset", false,-1);
    tracep->declBus(c+93,"branch_target", false,-1, 31,0);
    tracep->declBit(c+104,"pc_src", false,-1);
    tracep->declBit(c+45,"id_ready", false,-1);
    tracep->declBit(c+43,"wb_valid", false,-1);
    tracep->declBit(c+42,"if_ready", false,-1);
    tracep->declBit(c+44,"if_valid", false,-1);
    tracep->declBus(c+40,"pc", false,-1, 31,0);
    tracep->declBus(c+41,"instr", false,-1, 31,0);
    tracep->declBit(c+46,"if_access_fault", false,-1);
    tracep->declBus(c+47,"if_fault_addr", false,-1, 31,0);
    tracep->declBus(c+48,"sram_araddr", false,-1, 31,0);
    tracep->declBit(c+49,"sram_arvalid", false,-1);
    tracep->declBit(c+150,"sram_arready", false,-1);
    tracep->declBus(c+151,"sram_rdata", false,-1, 31,0);
    tracep->declBit(c+152,"sram_rvalid", false,-1);
    tracep->declBit(c+50,"sram_rready", false,-1);
    tracep->declBus(c+153,"sram_rresp", false,-1, 1,0);
    tracep->declBus(c+1,"sram_awaddr", false,-1, 31,0);
    tracep->declBit(c+2,"sram_awvalid", false,-1);
    tracep->declBit(c+186,"sram_awready", false,-1);
    tracep->declBus(c+3,"sram_wdata", false,-1, 31,0);
    tracep->declBus(c+4,"sram_wstrb", false,-1, 3,0);
    tracep->declBit(c+5,"sram_wvalid", false,-1);
    tracep->declBit(c+187,"sram_wready", false,-1);
    tracep->declBus(c+188,"sram_bresp", false,-1, 1,0);
    tracep->declBit(c+189,"sram_bvalid", false,-1);
    tracep->declBit(c+6,"sram_bready", false,-1);
    tracep->declBus(c+105,"state", false,-1, 31,0);
    tracep->declBus(c+106,"next_state", false,-1, 31,0);
    tracep->declBus(c+208,"rresp", false,-1, 1,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("mem_stage ");
    tracep->declBit(c+183,"clk", false,-1);
    tracep->declBit(c+184,"reset", false,-1);
    tracep->declBit(c+70,"ex_valid", false,-1);
    tracep->declBit(c+71,"mem_ready", false,-1);
    tracep->declBit(c+74,"wb_ready", false,-1);
    tracep->declBit(c+73,"mem_valid", false,-1);
    tracep->declBit(c+60,"MemRead", false,-1);
    tracep->declBit(c+59,"MemWrite", false,-1);
    tracep->declBus(c+107,"addr", false,-1, 31,0);
    tracep->declBus(c+66,"data_in", false,-1, 31,0);
    tracep->declBus(c+62,"MemLen", false,-1, 2,0);
    tracep->declBus(c+72,"data_out", false,-1, 31,0);
    tracep->declBit(c+75,"load_access_fault", false,-1);
    tracep->declBit(c+76,"store_access_fault", false,-1);
    tracep->declBus(c+77,"mem_fault_addr", false,-1, 31,0);
    tracep->declBus(c+78,"sram_araddr", false,-1, 31,0);
    tracep->declBit(c+79,"sram_arvalid", false,-1);
    tracep->declBit(c+154,"sram_arready", false,-1);
    tracep->declBus(c+155,"sram_rdata", false,-1, 31,0);
    tracep->declBit(c+156,"sram_rvalid", false,-1);
    tracep->declBit(c+80,"sram_rready", false,-1);
    tracep->declBus(c+157,"sram_rresp", false,-1, 1,0);
    tracep->declBus(c+81,"sram_awaddr", false,-1, 31,0);
    tracep->declBit(c+82,"sram_awvalid", false,-1);
    tracep->declBit(c+158,"sram_awready", false,-1);
    tracep->declBus(c+83,"sram_wdata", false,-1, 31,0);
    tracep->declBus(c+84,"sram_wstrb", false,-1, 3,0);
    tracep->declBit(c+85,"sram_wvalid", false,-1);
    tracep->declBit(c+159,"sram_wready", false,-1);
    tracep->declBus(c+160,"sram_bresp", false,-1, 1,0);
    tracep->declBit(c+161,"sram_bvalid", false,-1);
    tracep->declBit(c+86,"sram_bready", false,-1);
    tracep->declBus(c+108,"state", false,-1, 31,0);
    tracep->declBus(c+109,"next_state", false,-1, 31,0);
    tracep->declBus(c+110,"delay", false,-1, 1,0);
    tracep->declBus(c+209,"DELAY_CYCLES", false,-1, 31,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("sram ");
    tracep->declBus(c+210,"ADDR_WIDTH", false,-1, 31,0);
    tracep->declBus(c+210,"DATA_WIDTH", false,-1, 31,0);
    tracep->declBus(c+211,"MAX_DELAY", false,-1, 31,0);
    tracep->declBus(c+212,"MIN_DELAY", false,-1, 31,0);
    tracep->declBit(c+183,"clk", false,-1);
    tracep->declBit(c+184,"reset", false,-1);
    tracep->declBus(c+162,"araddr", false,-1, 31,0);
    tracep->declBit(c+163,"arvalid", false,-1);
    tracep->declBit(c+7,"arready", false,-1);
    tracep->declBus(c+9,"rdata", false,-1, 31,0);
    tracep->declBit(c+10,"rvalid", false,-1);
    tracep->declBit(c+164,"rready", false,-1);
    tracep->declBus(c+8,"rresp", false,-1, 1,0);
    tracep->declBus(c+165,"awaddr", false,-1, 31,0);
    tracep->declBit(c+166,"awvalid", false,-1);
    tracep->declBit(c+11,"awready", false,-1);
    tracep->declBus(c+167,"wdata", false,-1, 31,0);
    tracep->declBus(c+168,"wstrb", false,-1, 3,0);
    tracep->declBit(c+169,"wvalid", false,-1);
    tracep->declBit(c+12,"wready", false,-1);
    tracep->declBus(c+13,"bresp", false,-1, 1,0);
    tracep->declBit(c+14,"bvalid", false,-1);
    tracep->declBit(c+170,"bready", false,-1);
    tracep->declBus(c+24,"sram_state", false,-1, 31,0);
    tracep->declBus(c+25,"next_sram_state", false,-1, 31,0);
    tracep->declBus(c+26,"LFSR", false,-1, 31,0);
    tracep->declBus(c+213,"random_delay", false,-1, 31,0);
    tracep->declBus(c+27,"araddr_reg", false,-1, 31,0);
    tracep->declBus(c+28,"awaddr_reg", false,-1, 31,0);
    tracep->declBus(c+29,"rdata_reg", false,-1, 31,0);
    tracep->declBus(c+30,"wdata_reg", false,-1, 31,0);
    tracep->declBus(c+31,"wstrb_reg", false,-1, 3,0);
    tracep->declBit(c+181,"addr_valid", false,-1);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("uart ");
    tracep->declBus(c+210,"ADDR_WIDTH", false,-1, 31,0);
    tracep->declBus(c+210,"DATA_WIDTH", false,-1, 31,0);
    tracep->declBus(c+211,"MAX_DELAY", false,-1, 31,0);
    tracep->declBus(c+212,"MIN_DELAY", false,-1, 31,0);
    tracep->declBit(c+183,"clk", false,-1);
    tracep->declBit(c+184,"reset", false,-1);
    tracep->declBus(c+171,"araddr", false,-1, 31,0);
    tracep->declBit(c+172,"arvalid", false,-1);
    tracep->declBit(c+15,"arready", false,-1);
    tracep->declBus(c+17,"rdata", false,-1, 31,0);
    tracep->declBit(c+18,"rvalid", false,-1);
    tracep->declBit(c+173,"rready", false,-1);
    tracep->declBus(c+16,"rresp", false,-1, 1,0);
    tracep->declBus(c+174,"awaddr", false,-1, 31,0);
    tracep->declBit(c+175,"awvalid", false,-1);
    tracep->declBit(c+19,"awready", false,-1);
    tracep->declBus(c+176,"wdata", false,-1, 31,0);
    tracep->declBus(c+177,"wstrb", false,-1, 3,0);
    tracep->declBit(c+178,"wvalid", false,-1);
    tracep->declBit(c+20,"wready", false,-1);
    tracep->declBus(c+21,"bresp", false,-1, 1,0);
    tracep->declBit(c+22,"bvalid", false,-1);
    tracep->declBit(c+179,"bready", false,-1);
    tracep->declBus(c+32,"uart_state", false,-1, 31,0);
    tracep->declBus(c+33,"next_uart_state", false,-1, 31,0);
    tracep->declBus(c+34,"LFSR", false,-1, 31,0);
    tracep->declBus(c+35,"araddr_reg", false,-1, 31,0);
    tracep->declBus(c+36,"awaddr_reg", false,-1, 31,0);
    tracep->declBus(c+37,"wdata_reg", false,-1, 31,0);
    tracep->declBus(c+38,"rdata_reg", false,-1, 31,0);
    tracep->declBus(c+39,"wstrb_reg", false,-1, 3,0);
    tracep->declBit(c+182,"addr_valid", false,-1);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("wb_stage ");
    tracep->declBit(c+183,"clk", false,-1);
    tracep->declBit(c+184,"reset", false,-1);
    tracep->declBit(c+73,"mem_valid", false,-1);
    tracep->declBit(c+42,"if_ready", false,-1);
    tracep->declBus(c+51,"opcode", false,-1, 6,0);
    tracep->declBus(c+56,"func3", false,-1, 2,0);
    tracep->declBus(c+54,"id_rd", false,-1, 4,0);
    tracep->declBit(c+58,"id_RegWrite", false,-1);
    tracep->declBus(c+52,"rs1", false,-1, 4,0);
    tracep->declBus(c+53,"rs2", false,-1, 4,0);
    tracep->declBus(c+40,"pc", false,-1, 31,0);
    tracep->declBus(c+55,"imm", false,-1, 31,0);
    tracep->declBit(c+68,"alu_zero", false,-1);
    tracep->declBit(c+69,"alu_less", false,-1);
    tracep->declBus(c+67,"alu_result", false,-1, 31,0);
    tracep->declBus(c+72,"data_out", false,-1, 31,0);
    tracep->declBus(c+65,"rs1_val", false,-1, 31,0);
    tracep->declBus(c+66,"rs2_val", false,-1, 31,0);
    tracep->declBit(c+74,"wb_ready", false,-1);
    tracep->declBit(c+43,"wb_valid", false,-1);
    tracep->declBus(c+88,"jal_target", false,-1, 31,0);
    tracep->declBus(c+89,"jalr_target", false,-1, 31,0);
    tracep->declBit(c+90,"is_jal", false,-1);
    tracep->declBit(c+91,"is_jalr", false,-1);
    tracep->declBit(c+92,"take_branch", false,-1);
    tracep->declBus(c+87,"wb_data", false,-1, 31,0);
    tracep->declBus(c+111,"state", false,-1, 31,0);
    tracep->declBus(c+112,"next_state", false,-1, 31,0);
    tracep->declBit(c+113,"RegWrite_wb", false,-1);
    tracep->declBus(c+114,"rd_wb", false,-1, 4,0);
    tracep->declBus(c+115,"rd_wb_pre", false,-1, 4,0);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+116+i*1,"regs", true,(i+0), 31,0);
    }
    tracep->declQuad(c+214,"btb_valid", false,-1, 63,0);
    tracep->declBus(c+148,"btb_index", false,-1, 5,0);
    tracep->declBus(c+149,"i", false,-1, 31,0);
    tracep->declBus(c+216,"j", false,-1, 31,0);
    tracep->popNamePrefix(2);
}

VL_ATTR_COLD void Vrv32e___024root__trace_init_top(Vrv32e___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vrv32e__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vrv32e___024root__trace_init_top\n"); );
    // Body
    Vrv32e___024root__trace_init_sub__TOP__0(vlSelf, tracep);
}

VL_ATTR_COLD void Vrv32e___024root__trace_full_top_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vrv32e___024root__trace_chg_top_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vrv32e___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/);

VL_ATTR_COLD void Vrv32e___024root__trace_register(Vrv32e___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vrv32e__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vrv32e___024root__trace_register\n"); );
    // Body
    tracep->addFullCb(&Vrv32e___024root__trace_full_top_0, vlSelf);
    tracep->addChgCb(&Vrv32e___024root__trace_chg_top_0, vlSelf);
    tracep->addCleanupCb(&Vrv32e___024root__trace_cleanup, vlSelf);
}

VL_ATTR_COLD void Vrv32e___024root__trace_full_sub_0(Vrv32e___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vrv32e___024root__trace_full_top_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vrv32e___024root__trace_full_top_0\n"); );
    // Init
    Vrv32e___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vrv32e___024root*>(voidSelf);
    Vrv32e__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vrv32e___024root__trace_full_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vrv32e___024root__trace_full_sub_0(Vrv32e___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    if (false && vlSelf) {}  // Prevent unused
    Vrv32e__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vrv32e___024root__trace_full_sub_0\n"); );
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullIData(oldp+1,(vlSelf->rv32e__DOT__ifu_sram_awaddr),32);
    bufp->fullBit(oldp+2,(vlSelf->rv32e__DOT__ifu_sram_awvalid));
    bufp->fullIData(oldp+3,(vlSelf->rv32e__DOT__ifu_sram_wdata),32);
    bufp->fullCData(oldp+4,(vlSelf->rv32e__DOT__ifu_sram_wstrb),4);
    bufp->fullBit(oldp+5,(vlSelf->rv32e__DOT__ifu_sram_wvalid));
    bufp->fullBit(oldp+6,(vlSelf->rv32e__DOT__ifu_sram_bready));
    bufp->fullBit(oldp+7,(vlSelf->rv32e__DOT__sram_arready));
    bufp->fullCData(oldp+8,(vlSelf->rv32e__DOT__sram_rresp),2);
    bufp->fullIData(oldp+9,(vlSelf->rv32e__DOT__sram_rdata),32);
    bufp->fullBit(oldp+10,(vlSelf->rv32e__DOT__sram_rvalid));
    bufp->fullBit(oldp+11,(vlSelf->rv32e__DOT__sram_awready));
    bufp->fullBit(oldp+12,(vlSelf->rv32e__DOT__sram_wready));
    bufp->fullCData(oldp+13,(vlSelf->rv32e__DOT__sram_bresp),2);
    bufp->fullBit(oldp+14,(vlSelf->rv32e__DOT__sram_bvalid));
    bufp->fullBit(oldp+15,(vlSelf->rv32e__DOT__uart_arready));
    bufp->fullCData(oldp+16,(vlSelf->rv32e__DOT__uart_rresp),2);
    bufp->fullIData(oldp+17,(vlSelf->rv32e__DOT__uart_rdata),32);
    bufp->fullBit(oldp+18,(vlSelf->rv32e__DOT__uart_rvalid));
    bufp->fullBit(oldp+19,(vlSelf->rv32e__DOT__uart_awready));
    bufp->fullBit(oldp+20,(vlSelf->rv32e__DOT__uart_wready));
    bufp->fullCData(oldp+21,(vlSelf->rv32e__DOT__uart_bresp),2);
    bufp->fullBit(oldp+22,(vlSelf->rv32e__DOT__uart_bvalid));
    bufp->fullCData(oldp+23,(vlSelf->rv32e__DOT__axi_arb__DOT__current_master),3);
    bufp->fullIData(oldp+24,(vlSelf->rv32e__DOT__sram__DOT__sram_state),32);
    bufp->fullIData(oldp+25,(vlSelf->rv32e__DOT__sram__DOT__next_sram_state),32);
    bufp->fullIData(oldp+26,(vlSelf->rv32e__DOT__sram__DOT__LFSR),32);
    bufp->fullIData(oldp+27,(vlSelf->rv32e__DOT__sram__DOT__araddr_reg),32);
    bufp->fullIData(oldp+28,(vlSelf->rv32e__DOT__sram__DOT__awaddr_reg),32);
    bufp->fullIData(oldp+29,(vlSelf->rv32e__DOT__sram__DOT__rdata_reg),32);
    bufp->fullIData(oldp+30,(vlSelf->rv32e__DOT__sram__DOT__wdata_reg),32);
    bufp->fullCData(oldp+31,(vlSelf->rv32e__DOT__sram__DOT__wstrb_reg),4);
    bufp->fullIData(oldp+32,(vlSelf->rv32e__DOT__uart__DOT__uart_state),32);
    bufp->fullIData(oldp+33,(vlSelf->rv32e__DOT__uart__DOT__next_uart_state),32);
    bufp->fullIData(oldp+34,(vlSelf->rv32e__DOT__uart__DOT__LFSR),32);
    bufp->fullIData(oldp+35,(vlSelf->rv32e__DOT__uart__DOT__araddr_reg),32);
    bufp->fullIData(oldp+36,(vlSelf->rv32e__DOT__uart__DOT__awaddr_reg),32);
    bufp->fullIData(oldp+37,(vlSelf->rv32e__DOT__uart__DOT__wdata_reg),32);
    bufp->fullIData(oldp+38,(vlSelf->rv32e__DOT__uart__DOT__rdata_reg),32);
    bufp->fullCData(oldp+39,(vlSelf->rv32e__DOT__uart__DOT__wstrb_reg),4);
    bufp->fullIData(oldp+40,(vlSelf->rv32e__DOT__pc),32);
    bufp->fullIData(oldp+41,(vlSelf->rv32e__DOT__instr),32);
    bufp->fullBit(oldp+42,(vlSelf->rv32e__DOT__if_ready));
    bufp->fullBit(oldp+43,(vlSelf->rv32e__DOT__wb_valid));
    bufp->fullBit(oldp+44,(vlSelf->rv32e__DOT__if_valid));
    bufp->fullBit(oldp+45,(vlSelf->rv32e__DOT__id_ready));
    bufp->fullBit(oldp+46,(vlSelf->rv32e__DOT__if_access_fault));
    bufp->fullIData(oldp+47,(vlSelf->rv32e__DOT__if_fault_addr),32);
    bufp->fullIData(oldp+48,(vlSelf->rv32e__DOT__ifu_sram_araddr),32);
    bufp->fullBit(oldp+49,(vlSelf->rv32e__DOT__ifu_sram_arvalid));
    bufp->fullBit(oldp+50,(vlSelf->rv32e__DOT__ifu_sram_rready));
    bufp->fullCData(oldp+51,(vlSelf->rv32e__DOT__opcode),7);
    bufp->fullCData(oldp+52,(vlSelf->rv32e__DOT__rs1),5);
    bufp->fullCData(oldp+53,(vlSelf->rv32e__DOT__rs2),5);
    bufp->fullCData(oldp+54,(vlSelf->rv32e__DOT__rd),5);
    bufp->fullIData(oldp+55,(vlSelf->rv32e__DOT__imm),32);
    bufp->fullCData(oldp+56,(vlSelf->rv32e__DOT__func3),3);
    bufp->fullCData(oldp+57,(vlSelf->rv32e__DOT__func7),7);
    bufp->fullBit(oldp+58,(vlSelf->rv32e__DOT__RegWrite));
    bufp->fullBit(oldp+59,(vlSelf->rv32e__DOT__MemWrite));
    bufp->fullBit(oldp+60,(vlSelf->rv32e__DOT__MemRead));
    bufp->fullCData(oldp+61,(vlSelf->rv32e__DOT__alu_op),4);
    bufp->fullCData(oldp+62,(vlSelf->rv32e__DOT__MemLen),3);
    bufp->fullBit(oldp+63,(vlSelf->rv32e__DOT__id_valid));
    bufp->fullBit(oldp+64,(vlSelf->rv32e__DOT__ex_ready));
    bufp->fullIData(oldp+65,(vlSelf->rv32e__DOT__rs1_val),32);
    bufp->fullIData(oldp+66,(vlSelf->rv32e__DOT__rs2_val),32);
    bufp->fullIData(oldp+67,(vlSelf->rv32e__DOT__alu_result),32);
    bufp->fullBit(oldp+68,(vlSelf->rv32e__DOT__alu_zero));
    bufp->fullBit(oldp+69,(vlSelf->rv32e__DOT__alu_less));
    bufp->fullBit(oldp+70,(vlSelf->rv32e__DOT__ex_valid));
    bufp->fullBit(oldp+71,(vlSelf->rv32e__DOT__mem_ready));
    bufp->fullIData(oldp+72,(vlSelf->rv32e__DOT__data_out),32);
    bufp->fullBit(oldp+73,(vlSelf->rv32e__DOT__mem_valid));
    bufp->fullBit(oldp+74,(vlSelf->rv32e__DOT__wb_ready));
    bufp->fullBit(oldp+75,(vlSelf->rv32e__DOT__load_access_fault));
    bufp->fullBit(oldp+76,(vlSelf->rv32e__DOT__store_access_fault));
    bufp->fullIData(oldp+77,(vlSelf->rv32e__DOT__mem_fault_addr),32);
    bufp->fullIData(oldp+78,(vlSelf->rv32e__DOT__mem_sram_araddr),32);
    bufp->fullBit(oldp+79,(vlSelf->rv32e__DOT__mem_sram_arvalid));
    bufp->fullBit(oldp+80,(vlSelf->rv32e__DOT__mem_sram_rready));
    bufp->fullIData(oldp+81,(vlSelf->rv32e__DOT__mem_sram_awaddr),32);
    bufp->fullBit(oldp+82,(vlSelf->rv32e__DOT__mem_sram_awvalid));
    bufp->fullIData(oldp+83,(vlSelf->rv32e__DOT__mem_sram_wdata),32);
    bufp->fullCData(oldp+84,(vlSelf->rv32e__DOT__mem_sram_wstrb),4);
    bufp->fullBit(oldp+85,(vlSelf->rv32e__DOT__mem_sram_wvalid));
    bufp->fullBit(oldp+86,(vlSelf->rv32e__DOT__mem_sram_bready));
    bufp->fullIData(oldp+87,(vlSelf->rv32e__DOT__wb_data),32);
    bufp->fullIData(oldp+88,(vlSelf->rv32e__DOT__jal_target),32);
    bufp->fullIData(oldp+89,(vlSelf->rv32e__DOT__jalr_target),32);
    bufp->fullBit(oldp+90,(vlSelf->rv32e__DOT__is_jal));
    bufp->fullBit(oldp+91,(vlSelf->rv32e__DOT__is_jalr));
    bufp->fullBit(oldp+92,(vlSelf->rv32e__DOT__take_branch));
    bufp->fullIData(oldp+93,(vlSelf->rv32e__DOT__branch_target),32);
    bufp->fullIData(oldp+94,(vlSelf->rv32e__DOT__ex_stage__DOT__state),32);
    bufp->fullIData(oldp+95,(vlSelf->rv32e__DOT__ex_stage__DOT__next_state),32);
    bufp->fullIData(oldp+96,(vlSelf->rv32e__DOT__id_stage__DOT__state),32);
    bufp->fullIData(oldp+97,(vlSelf->rv32e__DOT__id_stage__DOT__next_state),32);
    bufp->fullIData(oldp+98,(vlSelf->rv32e__DOT__id_stage__DOT__immI),32);
    bufp->fullIData(oldp+99,((0xfffff000U & vlSelf->rv32e__DOT__instr)),32);
    bufp->fullIData(oldp+100,((((- (IData)((vlSelf->rv32e__DOT__instr 
                                            >> 0x1fU))) 
                                << 0xcU) | ((0xfe0U 
                                             & (vlSelf->rv32e__DOT__instr 
                                                >> 0x14U)) 
                                            | (0x1fU 
                                               & (vlSelf->rv32e__DOT__instr 
                                                  >> 7U))))),32);
    bufp->fullIData(oldp+101,((((- (IData)((vlSelf->rv32e__DOT__instr 
                                            >> 0x1fU))) 
                                << 0xcU) | ((0x800U 
                                             & (vlSelf->rv32e__DOT__instr 
                                                << 4U)) 
                                            | ((0x7e0U 
                                                & (vlSelf->rv32e__DOT__instr 
                                                   >> 0x14U)) 
                                               | (0x1eU 
                                                  & (vlSelf->rv32e__DOT__instr 
                                                     >> 7U)))))),32);
    bufp->fullIData(oldp+102,((((- (IData)((vlSelf->rv32e__DOT__instr 
                                            >> 0x1fU))) 
                                << 0x14U) | ((0xff000U 
                                              & vlSelf->rv32e__DOT__instr) 
                                             | ((0x800U 
                                                 & (vlSelf->rv32e__DOT__instr 
                                                    >> 9U)) 
                                                | (0x7feU 
                                                   & (vlSelf->rv32e__DOT__instr 
                                                      >> 0x14U)))))),32);
    bufp->fullCData(oldp+103,(vlSelf->rv32e__DOT__id_stage__DOT__get_opcode),5);
    bufp->fullBit(oldp+104,(vlSelf->rv32e__DOT____Vcellinp__if_stage__pc_src));
    bufp->fullIData(oldp+105,(vlSelf->rv32e__DOT__if_stage__DOT__state),32);
    bufp->fullIData(oldp+106,(vlSelf->rv32e__DOT__if_stage__DOT__next_state),32);
    bufp->fullIData(oldp+107,(vlSelf->rv32e__DOT____Vcellinp__mem_stage__addr),32);
    bufp->fullIData(oldp+108,(vlSelf->rv32e__DOT__mem_stage__DOT__state),32);
    bufp->fullIData(oldp+109,(vlSelf->rv32e__DOT__mem_stage__DOT__next_state),32);
    bufp->fullCData(oldp+110,(vlSelf->rv32e__DOT__mem_stage__DOT__delay),2);
    bufp->fullIData(oldp+111,(vlSelf->rv32e__DOT__wb_stage__DOT__state),32);
    bufp->fullIData(oldp+112,(vlSelf->rv32e__DOT__wb_stage__DOT__next_state),32);
    bufp->fullBit(oldp+113,(vlSelf->rv32e__DOT__wb_stage__DOT__RegWrite_wb));
    bufp->fullCData(oldp+114,(vlSelf->rv32e__DOT__wb_stage__DOT__rd_wb),5);
    bufp->fullCData(oldp+115,(vlSelf->rv32e__DOT__wb_stage__DOT__rd_wb_pre),5);
    bufp->fullIData(oldp+116,(vlSelf->rv32e__DOT__wb_stage__DOT__regs[0]),32);
    bufp->fullIData(oldp+117,(vlSelf->rv32e__DOT__wb_stage__DOT__regs[1]),32);
    bufp->fullIData(oldp+118,(vlSelf->rv32e__DOT__wb_stage__DOT__regs[2]),32);
    bufp->fullIData(oldp+119,(vlSelf->rv32e__DOT__wb_stage__DOT__regs[3]),32);
    bufp->fullIData(oldp+120,(vlSelf->rv32e__DOT__wb_stage__DOT__regs[4]),32);
    bufp->fullIData(oldp+121,(vlSelf->rv32e__DOT__wb_stage__DOT__regs[5]),32);
    bufp->fullIData(oldp+122,(vlSelf->rv32e__DOT__wb_stage__DOT__regs[6]),32);
    bufp->fullIData(oldp+123,(vlSelf->rv32e__DOT__wb_stage__DOT__regs[7]),32);
    bufp->fullIData(oldp+124,(vlSelf->rv32e__DOT__wb_stage__DOT__regs[8]),32);
    bufp->fullIData(oldp+125,(vlSelf->rv32e__DOT__wb_stage__DOT__regs[9]),32);
    bufp->fullIData(oldp+126,(vlSelf->rv32e__DOT__wb_stage__DOT__regs[10]),32);
    bufp->fullIData(oldp+127,(vlSelf->rv32e__DOT__wb_stage__DOT__regs[11]),32);
    bufp->fullIData(oldp+128,(vlSelf->rv32e__DOT__wb_stage__DOT__regs[12]),32);
    bufp->fullIData(oldp+129,(vlSelf->rv32e__DOT__wb_stage__DOT__regs[13]),32);
    bufp->fullIData(oldp+130,(vlSelf->rv32e__DOT__wb_stage__DOT__regs[14]),32);
    bufp->fullIData(oldp+131,(vlSelf->rv32e__DOT__wb_stage__DOT__regs[15]),32);
    bufp->fullIData(oldp+132,(vlSelf->rv32e__DOT__wb_stage__DOT__regs[16]),32);
    bufp->fullIData(oldp+133,(vlSelf->rv32e__DOT__wb_stage__DOT__regs[17]),32);
    bufp->fullIData(oldp+134,(vlSelf->rv32e__DOT__wb_stage__DOT__regs[18]),32);
    bufp->fullIData(oldp+135,(vlSelf->rv32e__DOT__wb_stage__DOT__regs[19]),32);
    bufp->fullIData(oldp+136,(vlSelf->rv32e__DOT__wb_stage__DOT__regs[20]),32);
    bufp->fullIData(oldp+137,(vlSelf->rv32e__DOT__wb_stage__DOT__regs[21]),32);
    bufp->fullIData(oldp+138,(vlSelf->rv32e__DOT__wb_stage__DOT__regs[22]),32);
    bufp->fullIData(oldp+139,(vlSelf->rv32e__DOT__wb_stage__DOT__regs[23]),32);
    bufp->fullIData(oldp+140,(vlSelf->rv32e__DOT__wb_stage__DOT__regs[24]),32);
    bufp->fullIData(oldp+141,(vlSelf->rv32e__DOT__wb_stage__DOT__regs[25]),32);
    bufp->fullIData(oldp+142,(vlSelf->rv32e__DOT__wb_stage__DOT__regs[26]),32);
    bufp->fullIData(oldp+143,(vlSelf->rv32e__DOT__wb_stage__DOT__regs[27]),32);
    bufp->fullIData(oldp+144,(vlSelf->rv32e__DOT__wb_stage__DOT__regs[28]),32);
    bufp->fullIData(oldp+145,(vlSelf->rv32e__DOT__wb_stage__DOT__regs[29]),32);
    bufp->fullIData(oldp+146,(vlSelf->rv32e__DOT__wb_stage__DOT__regs[30]),32);
    bufp->fullIData(oldp+147,(vlSelf->rv32e__DOT__wb_stage__DOT__regs[31]),32);
    bufp->fullCData(oldp+148,((0x3fU & (vlSelf->rv32e__DOT__pc 
                                        >> 2U))),6);
    bufp->fullIData(oldp+149,(vlSelf->rv32e__DOT__wb_stage__DOT__i),32);
    bufp->fullBit(oldp+150,(vlSelf->rv32e__DOT__ifu_sram_arready));
    bufp->fullIData(oldp+151,(vlSelf->rv32e__DOT__ifu_sram_rdata),32);
    bufp->fullBit(oldp+152,(vlSelf->rv32e__DOT__ifu_sram_rvalid));
    bufp->fullCData(oldp+153,(vlSelf->rv32e__DOT__ifu_sram_rresp),2);
    bufp->fullBit(oldp+154,(vlSelf->rv32e__DOT__mem_sram_arready));
    bufp->fullIData(oldp+155,(vlSelf->rv32e__DOT__mem_sram_rdata),32);
    bufp->fullBit(oldp+156,(vlSelf->rv32e__DOT__mem_sram_rvalid));
    bufp->fullCData(oldp+157,(vlSelf->rv32e__DOT__mem_sram_rresp),2);
    bufp->fullBit(oldp+158,(vlSelf->rv32e__DOT__mem_sram_awready));
    bufp->fullBit(oldp+159,(vlSelf->rv32e__DOT__mem_sram_wready));
    bufp->fullCData(oldp+160,(vlSelf->rv32e__DOT__mem_sram_bresp),2);
    bufp->fullBit(oldp+161,(vlSelf->rv32e__DOT__mem_sram_bvalid));
    bufp->fullIData(oldp+162,(vlSelf->rv32e__DOT__sram_araddr),32);
    bufp->fullBit(oldp+163,(vlSelf->rv32e__DOT__sram_arvalid));
    bufp->fullBit(oldp+164,(vlSelf->rv32e__DOT__sram_rready));
    bufp->fullIData(oldp+165,(vlSelf->rv32e__DOT__sram_awaddr),32);
    bufp->fullBit(oldp+166,(vlSelf->rv32e__DOT__sram_awvalid));
    bufp->fullIData(oldp+167,(vlSelf->rv32e__DOT__sram_wdata),32);
    bufp->fullCData(oldp+168,(vlSelf->rv32e__DOT__sram_wstrb),4);
    bufp->fullBit(oldp+169,(vlSelf->rv32e__DOT__sram_wvalid));
    bufp->fullBit(oldp+170,(vlSelf->rv32e__DOT__sram_bready));
    bufp->fullIData(oldp+171,(vlSelf->rv32e__DOT__uart_araddr),32);
    bufp->fullBit(oldp+172,(vlSelf->rv32e__DOT__uart_arvalid));
    bufp->fullBit(oldp+173,(vlSelf->rv32e__DOT__uart_rready));
    bufp->fullIData(oldp+174,(vlSelf->rv32e__DOT__uart_awaddr),32);
    bufp->fullBit(oldp+175,(vlSelf->rv32e__DOT__uart_awvalid));
    bufp->fullIData(oldp+176,(vlSelf->rv32e__DOT__uart_wdata),32);
    bufp->fullCData(oldp+177,(vlSelf->rv32e__DOT__uart_wstrb),4);
    bufp->fullBit(oldp+178,(vlSelf->rv32e__DOT__uart_wvalid));
    bufp->fullBit(oldp+179,(vlSelf->rv32e__DOT__uart_bready));
    bufp->fullCData(oldp+180,(vlSelf->rv32e__DOT__axi_arb__DOT__next_master),3);
    bufp->fullBit(oldp+181,(vlSelf->rv32e__DOT__sram__DOT__addr_valid));
    bufp->fullBit(oldp+182,(vlSelf->rv32e__DOT__uart__DOT__addr_valid));
    bufp->fullBit(oldp+183,(vlSelf->clk));
    bufp->fullBit(oldp+184,(vlSelf->reset));
    bufp->fullIData(oldp+185,(vlSelf->rv32e__DOT__trap_pc),32);
    bufp->fullBit(oldp+186,(vlSelf->rv32e__DOT__ifu_sram_awready));
    bufp->fullBit(oldp+187,(vlSelf->rv32e__DOT__ifu_sram_wready));
    bufp->fullCData(oldp+188,(vlSelf->rv32e__DOT__ifu_sram_bresp),2);
    bufp->fullBit(oldp+189,(vlSelf->rv32e__DOT__ifu_sram_bvalid));
    bufp->fullBit(oldp+190,(vlSelf->rv32e__DOT__reg_valid));
    bufp->fullBit(oldp+191,(vlSelf->rv32e__DOT__reg_ready));
    bufp->fullCData(oldp+192,(vlSelf->rv32e__DOT__rd_wb),5);
    bufp->fullBit(oldp+193,(vlSelf->rv32e__DOT__RegWrite_wb));
    bufp->fullBit(oldp+194,(vlSelf->rv32e__DOT__wb_MemRead));
    bufp->fullBit(oldp+195,(vlSelf->rv32e__DOT__wb_MemWrite));
    bufp->fullCData(oldp+196,(vlSelf->rv32e__DOT__wb_MemLen),3);
    bufp->fullIData(oldp+197,(vlSelf->rv32e__DOT__wb_addr),32);
    bufp->fullIData(oldp+198,(vlSelf->rv32e__DOT__wb_data_in),32);
    bufp->fullCData(oldp+199,(0U),3);
    bufp->fullCData(oldp+200,(1U),3);
    bufp->fullCData(oldp+201,(2U),3);
    bufp->fullCData(oldp+202,(3U),3);
    bufp->fullCData(oldp+203,(4U),3);
    bufp->fullCData(oldp+204,(1U),2);
    bufp->fullCData(oldp+205,(2U),2);
    bufp->fullCData(oldp+206,(0U),2);
    bufp->fullIData(oldp+207,(0U),32);
    bufp->fullCData(oldp+208,(vlSelf->rv32e__DOT__if_stage__DOT__rresp),2);
    bufp->fullIData(oldp+209,(3U),32);
    bufp->fullIData(oldp+210,(0x20U),32);
    bufp->fullIData(oldp+211,(4U),32);
    bufp->fullIData(oldp+212,(1U),32);
    bufp->fullIData(oldp+213,(vlSelf->rv32e__DOT__sram__DOT__random_delay),32);
    bufp->fullQData(oldp+214,(vlSelf->rv32e__DOT__wb_stage__DOT__btb_valid),64);
    bufp->fullIData(oldp+216,(vlSelf->rv32e__DOT__wb_stage__DOT__j),32);
}
